### ISSUE TITLE
Narrative Cartography Assignment: Resources & Discussions

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#30]
Hey @mapschool/infdpg16! 👋 

Hope everyone has been thinking through their topics for the Narrative Cartography Assignment. Let’s use this ticket to share interesting examples, reference papers and for any other discussions around data/design/code feedback.

This assignment is anchored by Prof. Chakradhar. Both @planemad & I will be happy to provide further feedback & support.

## Major dates

- 9th Jan — Checkpoint with @planemad, brainstorming on topics
- 12th Jan — Checkpoint with @rasagy, finalizing topics
- 17th Jan — Checkpoint with @rasagy, sharing [storyboards](https://in.pinterest.com/search/pins/?q=storyboard%20sketch%20narrative&rs=typed&term_meta[]=storyboard%7Ctyped&term_meta[]=sketch%7Ctyped&term_meta[]=narrative%7Ctyped)
- 24th Jan — Checkpoint with @planemad, sharing the narrative as a video

**Comment by rasagy** [comment]
## Inspiring projects

Here are some of the projects we saw in the class (5th Jan):

1. [Snow Fall, by NY Times](http://www.nytimes.com/projects/2012/snow-fall/) — One of the first digital journalism piece that uses a mix of photos, videos, maps and more. [This won a Pulitzer](https://en.wikipedia.org/wiki/2013_Pulitzer_Prize#Journalism), and led to [a lot](https://www.theatlantic.com/technology/archive/2012/12/new-york-times-snow-fall-feature/320253/) [of conversations](http://multimediashooter.com/wp/2013/04/21/the-snow-fall-effect-and-dissecting-the-multimedia-longform-narrative/) & [critiques](https://www.theatlantic.com/business/archive/2012/12/snow-fall-isnt-the-future-of-journalism/266555/).
2. [A rogue state along the river, by NY Times](https://www.nytimes.com/interactive/2014/07/03/world/middleeast/syria-iraq-isis-rogue-state-along-two-rivers.html?smid=tw-nytimes&_r=1) — Uses a long, scrollable satellite imagery annotated with images & details, along with a thumbnail map for context. _(Might not load well on NID internet)_
3. [Rewind the Red Planet, by NatGeo](https://www.nationalgeographic.com/science/2016/11/exploring-mars-map-panorama-pictures/) — Maps don’t have to be just of earth! This scrollable piece shows how Mars landscape has changed over time.
4. [My dear little Nelly, using Neatline](http://hotchkiss.neatline.org/neatline-exhibits/show/my-dear-little-nelly/fullscreen) — Overlays a letter written by Civil War cartographer Jedediah Hotchkiss on a map for explaining the Battle of Fredericksburg.
5. [The Geographic Divide of Oscar Films, on Pudding.cool](https://pudding.cool/2017/02/oscars_so_mapped/) — How static map visualizations can be used in a narrative with minor interactivity (& GIFs!). An alternative to small multiples.
6. [A Nation Divided, by Zeit](http://www.zeit.de/feature/german-unification-a-nation-divided) — Another example of scrolling through a set of hexbin maps.
1. [The Great Out-of-State Migration, by NY Times](https://www.nytimes.com/interactive/2016/08/26/us/college-student-migration.html) — A narrative using flow maps and scrolling through small multiples.
1. [Pipeline accidents](http://www.pipelineaccidentshappen.com/#/) — Proportional symbol map that lets you scroll through years.
1. [The New Trade Routes: Silk Road Corridor, by Financial Times](https://ig.ft.com/sites/special-reports/one-belt-one-road/) — Scroll through the text to see the map (camera) move around and highlight different parts of the region.
1. [What’s your favorite place in the world, by students in AmyLee’s MICA class](https://blog.mapbox.com/whats-your-favorite-place-in-the-world-96fd9de5336) — Good collection of personal narratives with the above [move-camera-on-scroll](https://www.mapbox.com/mapbox-gl-js/example/scroll-fly-to/) technique.
1. [Live air quality of the world](http://ocsidlab.github.io/earthmap/#2.95/25.50/64.53)
1. [World railway map](http://shvrm.github.io/railway/#2.5/11.70/35.96)
1. [Indian Railway Network](http://ruchikavn.github.io/indianrailwaymap/#4.19/22.829/72.887)

Examples discussed on 17th Jan:
1. [Comsology to Cartography: A cultural journey of Indian Maps, by Google Cultural Institute](https://www.google.com/culturalinstitute/beta/exhibit/wwICYzB2dW2HLQ)
1. [Koya Bound, by Craig Mod & Dan Rubin](https://walkkumano.com/)
1. [3D Terrain example](https://www.mapbox.com/bites/00332/#14.7341/-25.3454/131.0366/3.1465/36) and [blog post by Peter Liu](https://blog.mapbox.com/bringing-3d-terrain-to-the-browser-with-three-js-410068138357)

## Reading + video references
1. [Map-Based Visual Storytelling: An Assessment of Emerging Design Considerations — Zihan Song](https://www.youtube.com/watch?v=bFXv9DXfZr4) — She evaluates Longform vs dynamic slideshow, but [this slide](https://www.youtube.com/watch?v=bFXv9DXfZr4&index=8&t=118s) shows 6 forms of map-based visual storytelling identified by [Robert Roth](https://geography.wisc.edu/gis/staff/roth-robert/)

## Code examples
Mapbox GL examples for:
- [Simple camera movements](https://www.mapbox.com/mapbox-gl-js/example/flyto-options/) ([code I wrote in class is here](https://jsfiddle.net/rasagy/tv84c41s/))
- [Scroll to move camera around](https://www.mapbox.com/mapbox-gl-js/example/scroll-fly-to/) (Used by [Amy Lee’s students](https://blog.mapbox.com/whats-your-favorite-place-in-the-world-96fd9de5336))
- Other [Mapbox GL examples](https://www.mapbox.com/mapbox-gl-js/examples) and [Studio tutorials](https://www.mapbox.com/help/studio-manual-tutorials/)

**Comment by aromalram** [comment]
Topic Selected is 

## Kashmir: Caught in Crossfire

The year 2013 was one of the lowest points for militancy in Jammu and Kashmir ever since militancy started. It took just three years for the situation to turn difficult in early 2016. More than 200,000 people came out to mourn and protest the death of a young Hizbul leader Burhan Wani including 12-13 year old kids in school uniform.There is no denying the fact that between 2013 and 2016, there has been a sea change in the Kashmir situation. So what went wrong?

## Storyboard

![bda website_2](https://user-images.githubusercontent.com/22998147/35026735-c889b050-fb72-11e7-8cd5-47e382762dd2.jpg)


## Updated Narrative

## Introduction

**Frame 1a - 2016 - Riots after death of Burhan Wani - Stats**
The Kashmir Valley, where the situation has been relatively normal since 2010, saw violent protests in 2016, following the killing of young Hizbul Mujahideen commander Burhan Wani by the security forces in July . More than 200,000 people came out to mourn and protest his death including 12-13 year old kids in school uniform.

Such was the situation that valley remained under 53 days of consecutive curfew, with the government having to rush in additional forces to contain the agitation. The unrest, which went on for months, resulted in the deaths of more than 85 civilians and left over 13,000 injured.

## History

**Frame 1b - Drastic Change in 3 years - Where did things go wrong?**
The year 2013 was one of the lowest points for militancy in Jammu and Kashmir ever since militancy started. It took just three years for the situation to turn difficult in early 2016.  There is no denying the fact that between 2013 and 2016, there has been a sea change in the Kashmir situation.

**Frame 2a - The present mass uprising in Kashmir and the overall phenomenon of cyclic protests are rooted in the complex socio-political history of the region.**

Frame 2b - History of Kashmir - 1947 - Partition - Accession of Kashmir -  War

Frame 2c - Entry of China - Aksai Chan and Karokoram Tract - Pak-China Economic Corridor

Frame 2d - Alleged Rigging of Election triggers mass protest. Pak and ISI uses the opportunity to create separatist movement and militancy.

Frame 2e- 1990 - Kashmiri Pandits faced large scale violence and ethnic cleansing from the extremists. they were threatened and forced to leave teh valley en mass (2.5-3 lac pandits fled overnight). There were public announcements made in papers and in loudspeakers in the valley. Many fled to Jammu. Many of them are still living in tents and camps even now after 25 years. 

Frame 2f - 1990 - Rising Militancy and the violence led to the govt of India pasing the armed forces (special powers) act (AFSPA) in J&K.

Frame 2e - Kargil War

## Other Factors

 ### Frame 3 - Pakistan army’s stake in the border - Every peace process followed by a setback/attack
Pakistan army has the single largest share of gdp of any country in the world. There is no country in the world whose army disposes of a larger percent of either the govts budget or its gdp. Hence Pakistan military to justify this disproportionate command of its nations resources, has to point to trouble on its frontiers. 

### Frame 4 - Rise Unattached Militants/ Native Militants 
Today, most of the people are unattached militants. Many of them don’t have any Pakistani connections. They are not linked to any of the groups like Lakshar or Jaish. They may have some connections with the Hizbul [Mujahideen]. So, we have anger amongst our own people, that is if we accept that Kashmir is our own. 

### Frame 5 - Change in economics
Nearly 25 percent of people between 18 and 29 years are unemployed in Jammu and Kashmir while the national average is around 13.5 per cent. Investment for the year 2015-16 came down to Rs 267 crore, whereas between 2009-10 and 2014-15, this was close to Rs 1,000 year on year. With respect to centrally sponsored schemes, this year, nearly 10,000 crores is being pumped in, but 70 per cent of which will be spent towards creating assets like roads.

### Frame 6 - Rise of the popular narrative being narrowed down to a binary—good or bad, nationalist or anti-national.
Nowadays, nobody wants to listen to a rational explanation, nobody is willing to listen to the other man’s point of view. People are branded anti-nationalists for having a liberal view

## Conclusion

### Frame 7 -  The need to start treating Kashmiris as one of our own.
	
This is turning into a battle for the minds of the Kashmiri youth - the third generation in independant kashmir. Using force of the kind employed against the Lashkar, Jaish and Hizbul against today’s 10 and 12-year-old schoolchildren would only inflame passions further. 

The first generation had faith in the leadership, the second generation was in search of new leaders and the third generation does not want to be led by any leader. They are desperate to end the status quo and tired of getting killed and humiliated on a daily basis. This generation is educated, confident, converses with the outside world, cherishes the values of equality and freedom, and wants to live a life of respect and dignity. 

India has decisively won the battle against the foreign-based militants and terror outfits from Pakistan, but it now confronts a far graver problem of winning over the youth of Kashmir before an entire generation gets detached from India, a most frightening prospect.

**Comment by vinodxyz** [comment]
**Marco Polo's Journey** 

I'm working on the narrative for Marco Polo's 26-year journey along the Silk Road, reaching China and Mongolia. There are several interesting stories, along the way. I also wish to cover Marco's influence on the development of European cartography.

**Storyboards & Frames:**
![notes 001](https://user-images.githubusercontent.com/15855154/35371334-7fb5adaa-01b9-11e8-963b-28853476b364.jpeg)

**Video Mockup**
https://vimeo.com/252650522

**Final**
https://www.behance.net/gallery/64983491/Travels-of-Marco-Polo-Narrative-Cartography

![](https://mir-s3-cdn-cf.behance.net/project_modules/fs/9afbb064983491.5ae81741e2c22.gif)

**Comment by Tumb13weed** [comment]
All That Glitters: Story of the Koh-i-Noor Diamond (working title)
Syamantak Gupta

My narrative follows the journey of the Koh-i-noor Diamond, one of the most famous jewels, whose many surfaces reflect history, society and politics. More than the hard facts (or should I say, the hardest facts, since it's a diamond?) it's the stories, fables, legends and rumours surrounding the enigmatic jewel, from ancient curses placed on it to the recent controversy regarding its ownership, that provide the potential for an interesting narrative. The story runs from the days of the Sultanate of Delhi, flows through the Mughal Empire and Colonial Rule, and reaches the finale in present day London.

**Comment by pkd2512** [comment]
## Race to the bottom of the World
### A narrative on the first successful expedition to the South Pole

> In the short Antarctic Summer of 1911-12, five Britons and five Norwegians raced each other to the bottom of the world. Only the Norwegians returned. What happened in the race?
  
The narrative will trace the routes taken by the two teams, the situations they braved and the hurdles they overcame, attempting to follow Roald Amundsen on his route of success!

## Building the narrative

![new doc 2018-01-17_2](https://user-images.githubusercontent.com/7580745/35026514-7f8dded6-fb71-11e7-9d8c-c25752a0fb43.jpg)
![new doc 2018-01-17_1 2](https://user-images.githubusercontent.com/7580745/35026568-e06f74c6-fb71-11e7-983a-3c22f61cc537.jpg)

@rasagy Can you share the links to the examples that you showed in the last class? Including the DEM maps of Antarctica?

**Comment by rasagy** [comment]
Thanks to everyone who shared their topic & details — can others in @mapschool/infdpg16 also post their topics by end of today's class? 🙇

**Comment by planemad** [comment]
Recommended resource: [A Cultural Journey of Indian Maps](https://www.google.com/culturalinstitute/beta/exhibit/wwICYzB2dW2HLQ)

<img width="530" alt="screen shot 2018-01-14 at 11 40 10 pm" src="https://user-images.githubusercontent.com/126868/34919504-3f772e84-f98b-11e7-81f2-775f004cdc74.png">

**Comment by holy-devil** [comment]
Rajshree:

**The Rise & Fall of British Raj** 

The narrative would revolve around how East India Company evolved from a trade based organization to a political power controlling Indian subcontinent. It would trace the events like battles/treaties/rebellions etc responsible for the rise and fall of the British power.

Few sketches:
![image](https://user-images.githubusercontent.com/4013612/35026549-c0b8254c-fb71-11e7-8055-c302cfb6afa7.png)
 
next frames would show the spread of British control (similar to spread of Roman Empire) along with details and few images to give the context of events.

It would go on to show key events leading to the fall of empire in 1947.

**Comment by BarshaP14** [comment]
**Around India in 80 Trains**
-----------------------------------------
Story is about the 40,000km adventurous journey in Indian Railways through eyes of a women tourist, Monisha Rajesh, from London(Indian origin). Taking a page from Jules Verne's classic tale, she embarked on an adventure around India in eighty trains. This narrative shows reality about two of India’s greatest assets – its people and its railways.

On the way, Monisha met a colourful cast of characters with epic stories of their own. She discovers that train travel is the best way to get to know India through the various kind of people that she meets.
She also finds enough courage to travel on her own, something that she had hesitated to do in the beginning.

This is an attempt to show 80 train routes, covering most of India with stories of people having mixed emotions from different regions.

Storyboards
----------------
![sketch2](https://user-images.githubusercontent.com/25925845/35027036-5acd0bb4-fb74-11e7-8710-5a6ef5c6166a.jpeg)
![sketch1](https://user-images.githubusercontent.com/25925845/35027044-66126da2-fb74-11e7-8f3e-ed675ef4bb46.jpeg)

**Comment by jasleen20** [comment]
**Nelson Mandela**
The narrative revolves aorund the events which took place that ultimately lead Nelson Mandela to become the first Black President of South Africa
  
![img_20180117_101059](https://user-images.githubusercontent.com/30645312/35026231-bc4ad38a-fb6f-11e7-9bc8-3858a4056c18.jpg)

**Comment by 5xza** [comment]
# Revival of ancient religions – Neo-paganism

## Abstract 
‘Pagan’ was the term given by Christian church to all other (polytheistic) religions. Paganism has broadly connoted the "religion of the peasantry", and for much of its history was a derogatory term. Pagans had no tradition of discourse about ritual or religious matters (apart from philosophical debate or antiquarian treatise), no organized system of beliefs to which they were asked to commit themselves, no authority-structure peculiar to the religious area, above all no commitment to a particular group of people or set of ideas other than their family and political context. 
With the rise of Christianity in the Roman empire around 313 AD, and the church’s fundamental need to spread it resulted in coercing the pagans to convert to Christianity. Since most Pagans are already polytheistic, they did not resist much to their baptism. 
In the 19th century, paganism was adopted as a self-descriptor by members of various artistic groups inspired by the ancient world. In the 20th century, it came to be applied as a self-description by practitioners of Modern Paganism or neopagan movements who incorporate beliefs or practices different from those in the main world religions, such as nature worship.
Read more at http://www.patheos.com/library/pagan

## Ancient paganism:

### Frame 1
Pagan population in pre-Christian times (highlighting ancient egyptian, semitic and Mesopotamian regions). Declined first in Europe with onset of Christianity. And later declined in the east-asia with Islam.

### Frame 2
Started reviving again during renaissance as Greco-Roman magic. Had more ethnic value than religious. Through romanticism in 18th-19th century, gave rise to modern paganism or Neo-paganism.

## Identified NP religions before WWII:

### Frame 3
Time line progression of Druidism (one of the first NP movements, and is still being practiced) and its transition from a non-religious society into a religious pagan occult.

### Frame 4
Distribution and progression of rise and decline of other NP religions - Druidism, Hermetic order of the dawn, Church of the Universal Bond, Adonism. Also, highlighting Armanism and Ariosophy that led to the roots of Nazi ideologies of Aryan supremacy. All except druidism became defunct after WWII.

## Identified NP religions after WWII:

### Frame 5
Timeline progression of Wicca, witch is the most popular neo-pagan religion in the UK and US currently). 

### Frame 6 
Cities having NP revolutions across all continents during late 20th century. (Regions including - Australia, German-speaking Europe, Greece, Hungary, Ireland, Latin Europe, Scandinavia, SA, Slavic Europe, UK, US)
Symbols are available online for most NP groups so intending to use that as the markers of their spread.

### Frame 7
Gender distribution of several religions like wicca and druid (wiccans are mostly females and druids are generally males). Color of circle represents the gender the size of circle represents percentage population.

_### Frame x (deferred due to lack of data) 
(colored points scattered on world map): colors representing the practices of each NP group and with lighter ones as positive ideas (feminism, environmentalism etc.) and darker one as negative ideas (like supremacy, slavery etc.). Most are positive with only few exceptions of negative._

### Frame 8 
Distribution of pagan adherents compared to other prime religions (Christianity, Islam, Buddhism and atheism). Yet to take a decision on how to show this visual.

![artboard 1 2x-100](https://user-images.githubusercontent.com/22995838/35146463-18db8816-fd31-11e7-91c4-018a034a951b.jpg)

**Comment by planemad** [comment]
@mapschool/infdpg16 for more single page map interactivity and visualizations examples, do check out https://www.mapbox.com/labs-sandbox/

![new1](https://user-images.githubusercontent.com/126868/35261420-07b013c4-0036-11e8-97a8-d6668094102b.gif)

**Comment by pkd2512** [comment]
[http://prasantakrdutta.com/print-maps/](url)

A modification of the Matthew Petroff map printing app. Add your Mapbox Access Token and the style url and voila!

Happy Printing 👍

**Comment by planemad** [comment]
An effective example of narrative cartography https://outrider.org/nuclear-weapons/interactive/bomb-blast/ 😱💣

**Comment by iamreetika** [comment]
Hi all @planemad @rasagy Please give feedback for my attempt at visualising **"MH370: The aircraft that went missing"**
I have structured the narrative in 5 parts:

Introduction:
![page 1](https://user-images.githubusercontent.com/22998482/39679207-8e937af2-51b7-11e8-9b3f-b535566c710d.png)

Journey:
![page 2 copy 2](https://user-images.githubusercontent.com/22998482/39679211-9a9fb482-51b7-11e8-8596-3d895fe5a876.png)
![page 2 copy 7](https://user-images.githubusercontent.com/22998482/39679216-a3a4f970-51b7-11e8-92d0-dc6e0828c088.png)

Search:
![page 2 copy 6](https://user-images.githubusercontent.com/22998482/39679220-ab460980-51b7-11e8-859f-9d2340c2af7b.png)

Debris:
![page 5 copy 2](https://user-images.githubusercontent.com/22998482/39679221-b3126f5a-51b7-11e8-8784-ab89710f7045.png)
![page 5 copy](https://user-images.githubusercontent.com/22998482/39679222-b467f0b4-51b7-11e8-9c7b-179ed10e1698.png)

Passengers:
![page 3](https://user-images.githubusercontent.com/22998482/39679233-bd532338-51b7-11e8-827e-0404d5b0154a.png)

**Comment by rasagy** [comment]
Thanks to everyone who took time to update the screens here — closing this but feel free to take a minute to update your work if you still haven’t! ;)
