### ISSUE TITLE
Apps with maps Assignment

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#31]
Hey @mapschool/infdpg16, let’s use this ticket to discuss the map UI assignment. 

The goal of the assignment is to pick a common use-case (booking a flight, finding a store to shop at, meeting people with shared interests etc.), research the UI of different apps that solve this use case, and explore how a well designed map with effective visualization & interactivity could lead to a better design.

The assignment has two major deliverables:
1. Competitive analysis of the apps in the domain
2. Your design solution with a map as a prototype

## Major dates

- 12th Jan — Checkpoint with @rasagy, brainstorming on topics
- 17th Jan — Checkpoint with @rasagy, Competitive analysis and paper sketches of your concept
- 24th Jan — Checkpoint with @planemad, mid/high fidelity prototypes

Like #30, this assignment is anchored by Prof. Chakradhar. Both @planemad & I will be happy to provide further feedback & support.

## Resources
- Slides from my lecture on [types of map visualizations](https://speakerdeck.com/rasagy/maps-data-a-voyage-across-the-world-of-geo-visualization)
- Slides from Michael Gaigg and Allan Laframboise’s talk on [Better UI & UX with maps](http://slides.com/alaframboise/betteruianduxformappingapps-part2#/)
- For @aromalram: [Compare old & proposed maps from Bengaluru Master Plan 2031, by Ooru](http://ooru.in/) and [Maps on I Change My City](https://www.ichangemycity.com/bangalore/map/landuse)
- For @faaizasaeed: [Map of world news, by EventRegistry](http://eventregistry.org/search)

Please post your topics as comments, and feel free to update the comment or post new comments to share progress/questions.

**Comment by vinodxyz** [comment]
## Connect to people with similar interests

An app that connects you to others of similar interests, around you. The existing app is: [Causr](https://causr.rusic.com/) 

How it works?
1. Update your status, with your interest (eg: dataviz)
2. See people with this interest, around you
3. Connect and chat

Currently, this app displays a list of folks around, after following the above steps.
This interface can be improved tremendously, with a map.


![eventbrite](https://user-images.githubusercontent.com/15855154/35026683-7a7c492c-fb72-11e7-87bd-5bda4e29a50c.jpg)
![flow](https://user-images.githubusercontent.com/15855154/35026684-7ac7b31c-fb72-11e7-84de-8493d3593812.jpg)
![meetup](https://user-images.githubusercontent.com/15855154/35026685-7b090f60-fb72-11e7-92a7-fc3dd04e803f.jpg)
![screensv1](https://user-images.githubusercontent.com/15855154/35026686-7b4cb06c-fb72-11e7-97e8-20b60d1b24bf.jpg)

**Comment by aromalram** [comment]
## A map based interface for BDA (Bangalore Development Authority) Website

BDA (Bangalore Develoment Authority) or any Urban Development Authority in India currently don't have a map based interface for giving out information. 

Since they deal with urban level data it would help a user better understand the urban level information that is laid out on a map including upcoming proposals, projects, landuse, events and etc. It could also be a part of a platform for the volunteers and citizens to mark any issues or problems to be brought to the concerned authority's notice.

It could help a citizen be better aware of the area around him and be connected with the upcoming plans and proposals of the urban development authority.

Possible Layers for a map: Land Use, Proposals, Environment Layers, Master Plans, Electoral Boundaries, Land/Property Records/Taxation, Community Participation


### Preliminary Wireframe

![bda website_1](https://user-images.githubusercontent.com/22998147/35026071-dfc47a60-fb6e-11e7-8fc3-4e7331cc25fa.jpg)

Wireframes

![0 grid 1440 1](https://user-images.githubusercontent.com/22998147/37252494-b452a26e-2547-11e8-837f-4dc85e6c76b1.png)

![0 grid 1440 2](https://user-images.githubusercontent.com/22998147/37252496-b47e3640-2547-11e8-9c13-d588c972aec0.png)

![0 grid 1440](https://user-images.githubusercontent.com/22998147/37252497-b4aaea5a-2547-11e8-9e80-a0a8ca528ce6.png)

**Comment by holy-devil** [comment]
**A map based interface feature for Nearbuy app/website**

What it does:
User can explore offers at restaurants, spas, gyms, movies, hotels etc. and purchase them.

Currently the app/website just lists the offers using card listing, the experience can be improved using map interface, thus making it truly 'nearbuy'.

Concept images:
![image](https://user-images.githubusercontent.com/4013612/35026205-95d1d8de-fb6f-11e7-9681-90e1202d09eb.png)
![image](https://user-images.githubusercontent.com/4013612/35026217-9e9b6ae8-fb6f-11e7-8c25-44b351cdf56c.png)

**Comment by BarshaP14** [comment]
**A map based interface for hotel booking apps like OYO Rooms**
---------------------------------------------------------------------
Need for improvisation:
1. With the help of map based interaction nearest hotels to any landmark could be shown in better way.
2. A clear comparison of distance and prices could be done.
3. Map look and feel could be customised according to the app.

Current situation:
On the home page primary Search for any hotel is done by asking nearest location name, and time period of stay. Then the complete list of hotels is displayed. Once you select a particular hotel and are done with booking it shows the location at the end.

**Comment by iamreetika** [comment]
A **map based UI for a medical app** that allows user:
- To find hospitals, clinics, diagnostic labs, doctors, medical stores around him/her
- To check if hospital/store is open at a particular time (in case of emergency / 24-7 pharmacy)
- To see availability of medicine entered in shops nearby (if possible)
- To find doctors with particular speciality around him on a map
- To help reach the location by giving options like navigation / cab booking

This can be explored for apps like Practo / 1mg / Netmeds / PharmEasy / Medlife.

**Comment by pkd2512** [comment]
## Flight booking and last mile travel to destination in a city

Flight booking apps can use a map based UI to show flights and prices which can be a more visual way of consuming the information over traditional table structure. Also, they can add a nice to have feature of suggesting a last mile transport from the airport to the destination.

**Comment by Tumb13weed** [comment]
*Finding that person is now a walk in the park. Literally.*

I'm thinking of an app for meeting people, which *matches you based on
places where you both like hanging out*. Be it this fancy café which is
your go-to place on a winter evening, or the quaint park that is lush with
blossoms in the wake of spring (and also fitness-conscious uncles who give
you judgmental stares).

*How the map aids the app*
Location is key in this app, and users are matched primarily by location.
This helps in several manners. Firstly, these locations are public, so the
chances of date-harassment are low. Second, the location is known and
familiar to the people who are meeting, so they do not feel the friction of
a new place. Third, places are* almost always* automatically matched with
an activity (for example, people probably go to a food street to eat), so
it helps with the "what do we do when we first meet?" bit. And last but not
the least, if it doesn't work out between you two, you know where to find
him on a Sunday evening (but make it look like an accident).

*How do you turn this on*
The app has three components - the map, an event dashboard and an instant
messenger.
The onboarding is as with any other dating app, with people providing their
basic information. From thereon, they are led to the map. Geographical
locations are mapped to activities, which are showed with icons (for
example, the icon of a bird on a lake suggesting birdwatching). If it's a
large area rather than an establishment, the map also helps pick a meeting
point (e.g. visiting Indiranagar? Meet outside McDonalds). Additionally, it
provides a list of upcoming events, like photowalks, poetry slams etc,
which again could serve as the place to meet. Finally, the instant
messenger helps users finalise on the finer details of the meetups.

>

**Comment by Tumb13weed** [comment]
## **Finding that person is now a walk in the park. Literally.**

I'm thinking of an app for meeting people, which **matches you based on places where you both like hanging out.** Be it this fancy café which is your go-to place on a winter evening, or the quaint park that is lush with blossoms in the wake of spring (and also fitness-conscious uncles who give you judgmental stares). 

**How the map aids the app**
Location is key in this app, and users are matched primarily by location. This helps in several manners. Firstly, these locations are public, so the chances of date-harassment are low. Second, the location is known and familiar to the people who are meeting, so they do not feel the friction of a new place. Third, places are _almost always_ automatically matched with an activity (for example, people probably go to a food street to eat), so it helps with the "what do we do when we first meet?" bit. And last but not the least, if it doesn't work out between you two, you know where to find him on a Sunday evening (just make sure you make it look like an accident).

**How do you turn this on**
The app has three components - the map, an event dashboard and an instant messenger.
The onboarding is as with any other dating app, with people providing their basic information. From thereon, they are led to the map. Geographical locations are mapped to activities, which are showed with icons (for example, the icon of a bird on a lake suggesting birdwatching). If it's a large area rather than an establishment, the map also helps pick a meeting point (e.g. visiting Indiranagar? Meet outside McDonalds). Additionally, it provides a list of upcoming events, like photowalks, poetry slams etc, which again could serve as the place to meet. Finally, the instant messenger helps users finalise on the finer details of the meetups.

**Comment by 5xza** [comment]
# Map intervention for news apps (like BBC, CNN etc):
### Feature requirement 
User can choose a location on map (point or area) and the list of news stories of that area should show in a chronological order.

### Feature highlights:

1. View news stories from a selected location.
2. View news stories from a selected area of interest (input range of location).
3. View archived news stories from a selected location/area of interest. (input date/range of dates)
4. Secondary importance: User being able to submit a news story tagged with a location. Users can view stories submitted by other users in their location based news.

![img_20180119_162903](https://user-images.githubusercontent.com/22995838/35147845-0c3c1de6-fd36-11e7-82da-7c53d823864f.jpg)

### Final update:
Updated with the final concept and screens. (I'm thinking of adding local weather to the app as well, but it's a completely new feature, so will be doing after jury :) )

<img width="1307" alt="slide 1" src="https://user-images.githubusercontent.com/22995838/38297835-47f01fa0-3813-11e8-8d66-0d4159f37db5.png">
<img width="1307" alt="slide 2" src="https://user-images.githubusercontent.com/22995838/38297836-481d2c84-3813-11e8-81ef-c2b675d39e4a.png">
<img width="1307" alt="slide 3" src="https://user-images.githubusercontent.com/22995838/38297837-484c2aa2-3813-11e8-9bde-864871b99f9b.png">
<img width="1307" alt="slide 4" src="https://user-images.githubusercontent.com/22995838/38297838-48de4f68-3813-11e8-9510-b5d5898475b4.png">

**Comment by rasagy** [comment]
Thanks to everyone who took time to update the screens here — closing this but feel free to take a minute to update your work if you still haven’t! ;)
