### ISSUE TITLE
GeoViz Critiques

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#52]
Hi everyone,

Let’s document our critique sessions on Github, like [your senior batches did last year](https://github.com/mapschool/course/issues/36). 

For each group, add in one comment these points for every visualization you picked:

1. Title of the viz, and url (along with one screenshot/gif)
1. Geo viz type (Cartogram/Choropleth/dot maps etc.)
1. Source of data and what the type of data visualized (ordinal/nominal/quantitative/qualitative…)
1. Visual encoding for each property (line, angle, color…)
1. Critique (How effective is it at what it aims to do? What works well, and what could be better?)

Feel free to edit your comment and update/add the rest of the visualizations if you have only two visualizations right now.

**Comment by rasagy** [comment]
Each of you can add a comment like this.
![image](https://user-images.githubusercontent.com/1117531/90500860-177b6580-e169-11ea-9972-c66a07187c61.png)

https://www.behance.net/gallery/14829307/Visualizing-Access-to-Drinking-Water-in-India

**Comment by mohakgulati99** [comment]
<h1>Alcohol Consumption in India (Men & Women)</h1>

![Alcohol](https://user-images.githubusercontent.com/55638531/90528526-5a046880-e190-11ea-88c6-7b4f3f83d483.png)
_(https://www.instagram.com/p/CDI9yJYJH-0/)_
The 2 images show state-wise percentage of men and women who consume alcohol in India.

<b>Type:</b> Choropleth, Visual Confirmation (Declarative & Data Driven)

<b>Source:</b> [National Family Health Survey (NFHS 4) 2015-16](http://rchiips.org/NFHS/NFHS-4Reports/India.pdf), Page 379

<b>Type of Data:</b> State and Gender (Nominal), % of people who drink alcohol (Quantitative)

<b>Visual Encoding:</b> Percentages from 0% to 60% are depicted using saturation and they've used 2 maps, one for each gender. They also mention the exact percentage on the states as well.

<b>Critique:</b> This visualization seems to make a very declarative statement while completely ignoring the social contexts of the raw data. The data does not factor in taboos or social customs in different states and ethnicities. For example, young women and men in India might be less inclined to say that they drink because their families might not be okay with that. One of the reasons the higher consumption rate for women in Arunachal Pradesh is due to the fact that people drink millet wine, a traditional form of alcohol. Families usually sit around the fire, dancing and consuming millet wine, hence people are more open about saying they consume alcohol. Similarly other states might have other customs.
Since the data is questionable without the social contexts, I believe the designer could have removed the state aspect and just looked at Men and Women's alcohol consumption based on the geography and climate. This could've been done with the use of a Cartogram. That would've given us interesting insights like whether people in cold areas drink more than those in coastal areas, etc.
<hr>
<b>Mohak Gulati 18U130018</b>

**Comment by parthob** [comment]
### World Population Cartogram

![image](https://user-images.githubusercontent.com/33090222/90542015-1e25cf00-e1a1-11ea-8742-f6723c21cdff.png)

The image shows visualisations of world population by country.

**Type**: Cartogram (Data Driven and Declarative)

**Source**: https://ourworldindata.org/world-population-cartogram

**Datatype**: Population data, country names and simplified borders.

**Visual Encoding**: Text on the map indicates the country and its population, and colour is used to differentiate between countries (and in cases where the country is too small to include text within borders, the colour provides a connection). Country borders are simplified using a square grid. 

**Critique**: The cartogram gives the viewer an accurate idea of the differences in population. Simplifying borders reduces visual overload, and retains an element of familiarity. However, because of the irregular shapes, it becomes difficult to compare with accuracy countries that are similarly sized but far apart on the map. 

The colours themselves seem to be chosen at random, fulfilling their primary purpose of differentiation, but I believe this could be used to add a dimension that isn't included in this cartogram: **the population density**. 

All-in-all, the cartogram fulfils its primary purpose - to give the reader an idea of population. There is population data by country, as well as metrics of continent-wise population scattered across the chart. It is incredibly easy to identify the most heavily populated countries, even with a quick glance. The lesser-populated require more careful reading to even identify by name.


**Parth Oberoi | 17U130004**

**Comment by Niharika-Mohile** [comment]
### **Why Measles May Just Be Getting Started**

![image](https://user-images.githubusercontent.com/69865621/90544231-7a3e2280-e1a4-11ea-8645-c30be3287161.png)

The image above shows the data visualization titled 'Why Measles May Just Be Getting Started', by Keith Collins, Adam Pearce and Drew Armstrong

**Type:** Dorling Cartogram (Data-driven and Declarative)

**Source:** https://www.bloomberg.com/graphics/2015-measles-outbreaks/

**Datatype:** Nominal (state name abbreviations) and Quantitative (quantity of measles infected persons in the state)

**Visual Encoding:** The map shows data from 2000-2015 of the number of people infected by measles in each state of the US. The **size** of each square shows the number of infected people, the two **letters** in the top left-hand corner of each square explain which state it corresponds to, and **colour** is used to distinguish between the years.

**Critique:** 
Note- Though the site has a series of related visualisations, I am analysing the selected one by itself

The visualization succeeds at showing its intent- the resurgence of prevalence in the united states, proving that it hasn't been fully eradicated. It also succeeds at showing the variance in measles outbreaks in the different states.

However, the cartogram lacks information on the number of persons encoded by a particular size of square; there is no legend for it. Another shortcoming is that it shows the number of infected people, not the number of infected people per capita. The sizes of Ohio and California are roughly equal, but the population of California is about 4 crores, whereas that of Ohio is about 1 crore. This means the likelihood of a Californian being infected is a quarter of the likelihood of an Ohioan. The visualisation fails to represent this- looking at the visualisation alone, you would feel the chances are equal.

Further along in the website, there does come a visualisation showing the measles vaccination rates per state. However, I feel this information should be incorporated into the above visualisation, as it would give a better idea of the relation between vaccination and disease spread, and may help against the anti-vaxxers' debate. 

**Niharika Mohile 18U130021**

**Comment by jeremyiype** [comment]
# Arteries of The City 

![South China Morning Post Graphics-01](https://user-images.githubusercontent.com/60372569/90599340-4d285900-e212-11ea-846b-cd63fa113c37.png)

[Source](https://multimedia.scmp.com/culture/article/SCMP-printed-graphics-memory/lonelyGraphics/201210A113.html)

This is a visualization of the flow and volume of vehicular traffic in Hong Kong in the years 2010-2011.

**Type**: Bivariate Flow Map

**Data types**: Location names (nominal), traffic volume (quantitative), change in traffic volume (comparative)

**Visual Encoding**: This visualization shows the amount of traffic on Hong Kong roads in 2011 and compares it to the same data from 2010. The amount of traffic on each road is represented by the thickness of the lines, and the variation between the two years is represented by the color of the line; the bluer the line, the less traffic compared to the previous year, and the redder the line the more traffic as compared to the previous year.

**Critique**: While the visualization is visually appealing and clean, it has a few flaws which, I believe, take away from its effectiveness and potential. While some locations are marked on the map, most of the map devoid of features which might provide context to the traffic flow. For example, an industrial area might have more heavy traffic than a suburb. Another potential flaw is the lack of any geographical features which explain a lot of Hong Kong's traffic issues. Another factor is the connection to the Chinese mainland which also affect the traffic at the ports of entry. 
While the comparison with the traffic rates of 2010 are interesting, unless a cause is attributed to the change, no real conclusions can be drawn from the visualization. Two years is too small of a sample size to indicate any changing trends.

**Cherian Jeremiah Iype** | 18U130012

**Comment by kumarrishabh0707** [comment]
# Share of the population using the Internet, 2017
![image](https://user-images.githubusercontent.com/16447438/90578863-f9058080-e1e1-11ea-9f09-1f39862f51ee.png)
![image](https://user-images.githubusercontent.com/16447438/90578956-3833d180-e1e2-11ea-9a82-d2f5dccb310f.png)
[Link](https://ourworldindata.org/grapher/share-of-individuals-using-the-internet?year=latest&time=earliest..latest&country=~IND)
[Data Source](https://datacatalog.worldbank.org/dataset/world-development-indicators)

Here's an interactive visualisation about the share of the population, for each country, using the Internet, 2017

**Type:** Interactive choropleth, Data-driven and declarative 

**Data types:** Country names with accurate borders (nominal), Share of population using internet from 0 to 100% (quantitative) mapped over time.

**Visual encoding:** This visualisation shows the share of the population using the internet using a colour saturation scale which is ranging from 0 to 100% for each year. When you hover over the country, it shows the name and the percentage of the users, with a small bar graph which compares it with the previous years. On clicking a country, it shows a line graph plotted against time which shows the variance of users over the years.

**Critique:** This visualisation offers a great overview of the relative usage and activity regarding the internet by plotting it against time, where we can see the share of users curve flattening out for western countries during the current era, whereas the developing countries are growing their numbers exponentially. I think a lot more insight could have achieved by absolute numbers, as the current encoding misrepresents the number of users for each country. The original intent of the creator was using technology adoption as a world development indicator, but it fails with certain sets of countries, especially developing countries who have very basic telecommunication infrastructure, as it just considers single instances of usage and not subscriptions and intensity of usage, which would have served better for the core intention. Countries like China also create a discrepancy in data, as they have access to an abridged and heavily censored version of the Internet.
I think a cartogram would have been a truer representation, with other data metrics like frequency of usage by people encoded into the map, to show technological adaption and growth of the countries.

**Comment by NiharikaK1543** [comment]
### [What is missing?](https://www.whatismissing.net/)
![Screenshot (233)](https://user-images.githubusercontent.com/60334656/90610283-d3e53200-e222-11ea-8fbe-de37d6716e00.png)

**GeoViz type-** Interactive Dot map using different Icons.
Visual confirmation- Data driven and declarative while, also aims to be Idea generation in abstract ways.
**Sources-** The sources of all articles and information are mentioned on the website and are different for different topics.
**Data type-**  
It is a memoir of sorts as stated by the designer to connect the affects of various natural and human induced changes on the habitats and species of animals across the world. It Is also an attempt to spread awareness, speculate and a call to action to prevent further loss and degradation of species and habitats. 
The entire chart is based on the following nominal datasets:
1.	TIMELINE- Timelines that share an in depth ecological history
2.	VIDEO- Videos that show species and habitats at risk
3.	STORIES- Historical and personal accounts of former abundance”
4.	CONSERVATION- Conservation efforts in place
5.	DISASTER- What species we lost or are losing
 Each of these five elements charted on the world map can also further be filtered based on five  subject filters i.e. species, extinct, habitat , anthropology and pollution.

**Visual encoding-** 
All the above mentioned elements are represented using small distinct round icons and the subsequent filter buttons are also distinct color coded icons.
Clicking on one elements on the map, opens up more information topics which can even further branch to more information topics in some cases.
**Critique-**
•	It’s supposed to be a memoir of species and habitats, so it’s  a very narrative and casual way of visualising such a huge amount of information.
•	Too many transitions, when you first load the visualisation everything is floating all over the map for good 10 seconds until things come at places and it looks very confusing.
•	The default visualisation when you haven’t selected any elements or further filters doesn’t show all the charted elements which could have been incorporated from the start.
•	The meaning of the elements are defined only at the start but once you start exploring the visualisation and want to get back to  it, its not possible unless you reload it. Also the titles of the elements are not very clear and can create confusion.
•	There are no visual or textual cues or instructions on how the filtering works. You have to click around, observe and explore on your own as to what’s happening on the map.
•	The only difference in the icons for VIDEO and STORIES is just the size of the circle. Confusion can be reduced using shapes different from each other.
•	The map is not  divided into countries which could’ve helped the audience with better navigation.
•	The information structuring into different elements is a bit confusing as to what are the things included in TIMELINE and in CONSERVATION and how do they not overlap. Better explanations on the datasets could have been provided.
•	Along with the data presented on the map there is other curated information tabs on the top right which you can explore to learn more about the steps we can take to save the environment and the current conditions our natural system is in.
•	In all I think it’s  a beautiful visualisation which does serve its purpose in spreading knowledge and awareness very narratively and lets the audience explore in different ways.

**Niharika Kumawat**, 18U130020

**Comment by SankalpoDas** [comment]
**### Language Map of India**

![Screenshot (129)](https://user-images.githubusercontent.com/69919031/90680782-02452a80-e280-11ea-88e1-b932e8e6f65f.png)

This map of India shows major language spoken in each state and union territory. 

**Source:**  https://www.mapsofindia.com/maps/india/indianlanguages.htm

**Type:** Choropleth

**Data type:** Nominal (states and languages)

**Visual encoding:** Colour (depicts language)

**Critique:** 
    This visualization depict the major languages spoken in different states in India, but it does so in a manner which is very inefficient and also contains information which whatsoever has no use in the given context. Showing just the major language of each state does not do justice to the title of the piece(even though the states may actually be divided based on linguistic groups). I feel the depiction of language spoken in a smaller region(not necessarily district) would have been a much better way to show the fact that India is a country of widely varied culture. Another issue is the selection of colour palette. Colours here are selected at random. Another dimension which could have been added is the classification of the languages and could be depicted by the use of an appropriate colour palatte. Also, there is no information on the population of people speaking each language, which can be an interesting topic for the viewers. Any visualization much contain information not more than what it is about. In that regard, this map has a lot of information visible which is absolutely not need in the context ie. the representation of bordering counties(China, Pakistan, etc.) and oceans, which only contributes to disrupting the aesthetic. The use of full names of each state could have been avoided which also contributes to the disrupting the aesthetic. I would like to end on the note that this was a good atempt, but it totally skips out one very strong point of India, our cultural divercity.

**Comment by MedhaviParasar** [comment]
# [Lowy Global Diplomacy Index](https://globaldiplomacyindex.lowyinstitute.org) 
<img width="1680" alt="Screenshot 2020-08-20 at 7 46 45 AM" src="https://user-images.githubusercontent.com/69924281/90709213-4e609100-e2b9-11ea-91f6-f1924f2ad78d.png">

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/69924281/90710400-eeb7b500-e2bb-11ea-8ab2-195d9931136d.gif)

**Visualization:**[ Lowy Global Diplomacy Index](https://globaldiplomacyindex.lowyinstitute.org)

**Geographical Visualization type:** Interactive Dot Map

**Data source:** [GLOBAL DIPLOMACY INDEX 2019](https://globaldiplomacyindex.lowyinstitute.org/downloads/LowyInstituteGlobalDiplomacyIndex_Methodology.pdf)

**Type of Data**: Ordinal, Quantitative

**Visual Encoding:** 1. Dots to indicate the location of posts (embassies, consulates, etc.). These dots are yellow in colour
2. Circles to indicate global network. The circles’ sizes vary based on rank the country has and the lines inside the circle indicate the actual number of networks they have. The lines also indicate the direction in which their embassies are (where the other country is). These circles with lines inside are blue in colour.
3. They have text on the left-hand side indicating more information and stats about the visualization, country, or post. It also lets you show or hide information by a few toggle buttons.
When you hover over either the circles or the dots, they draw lines to connect you to the other countries which have their embassies or the origin country of the embassy connected to the post. It also shows you the relevant text pertaining to that country or post.

**Critique:** This visualization aims to highlight gaps and concentrations in diplomatic networks, and indicates strengths and weaknesses in geographic coverage and geopolitical reach. Users can view the global map of networks, select and view individual country networks on the map, prepare side-by-side comparisons of networks, as well as see diplomatic representations by cities for three years (2016, 2017, 2019). For the most part, it accomplishes what it sets out to achieve. It does show us the gaps and concentrations, even shows what directions these connections mostly go towards for their respective countries.

However, the circles and dots get very crowded in some areas making it difficult to interact with the data. The circles also get too small in some cases to be able to make out the number of lines and in some circles have so many connections, the lines are too crowded to see the number of connections. It also feels as if the countries get a little lost as the borders distinguishing countries are barely visible and in some cases, the countries are completely hidden by overlapping circles. If the information communicated by the circles could be replaced with another method of visual encoding, it might declutter the map and make it a little easier to interact with. We could maybe put a choropleth instead of the circle but then we lose the direction aspect the circles showed us. Maybe we could incorporate both the circle and the choropleth but it might make the visualization too confusing.

**Comment by itsalwaysatul** [comment]
# Global Human Journey
![33313](https://user-images.githubusercontent.com/68927529/90708974-c7131d80-e2b8-11ea-851f-7ac033f960d3.jpg)
_MAP BY NATIONAL GEOGRAPHIC MAGAZINE_

This is a Static + Animated map depicting the movement of the human species out of Africa.

**Source:**  [Video](https://www.nationalgeographic.org/media/global-human-journey/#human-migrations), [Photograph](https://www.nationalgeographic.org/media/global-human-journey/#global-human-journey)

**Type:** Lines on a map + Flow

**Data Type:** Predicted path of movement[_Nominal_], Mapped over time[_Ordinal_], Name of some locations[_Nominal_], Numbers ranking the earliest to youngest[_Ordinal_].

**Visual Encoding:** The flow of the lines depict the path early human took to migrate to different continents and in the video the arrows are animated to depict the time they took. In the stationary map, the time is depicted through colour where blue is oldest and red is youngest.

**Critique:** The visualization attempts to portray the path of early human migration; however, it can confuse the viewer through misrepresentation and inefficient tactics. Therefore, the overall map is shifted to the left and is different from the standard maps we are used to seeing. While this is done to make room for the arrows, the map could be made more relatable by using common borders, landmarks, or historical landmarks of the time from where this data was collected. In the time being depicted by the map, the geography was very different, and the presence of the different ice sheets and lower sea levels should be depicted. The present-day map cannot inform the user of how these movements took place, and if there is any comparison between modern-day and these times, it should be highlighted.

There were different modes of transport being used, and a single arrow cannot depict the mode of transportation. The encoding problem of depicting time through color also proves to be ineffective. Since the time is spread over a range, a single color cannot depict it. Furthermore, the arrows' width is confusing the user to think there is some form of encoding while it only serves a visual purpose. The arrows themselves have been curved to appeal to the user, but it hinders the actual data. In the animation, the arrows are starting and ending at specific points, and it would be helpful to display those points such that the viewers can distinguish where these connections are.

**Comment by praffi2000** [comment]
**Where The Wild Things Glow**

![image](https://user-images.githubusercontent.com/60361539/90712890-a26f7380-e2c1-11ea-9eab-961645b409ac.png)
Full-res: [https://pbs.twimg.com/media/D_mHNhoXUAA00zI.jpg:large](url)

**Type:** Dot map with colours
**Source:** [https://public.tableau.com/views/WhereTheWildThingsGlow/Tester?:embed=y&:display_count=yes&publish=yes&:toolbar=no&:origin=viz_share_link&:showVizHome=no](url)
**Nominal/ Qualitative.**


**Visual Encoding:**  The data shows where the bioluminescence in different organisms can be seen in the South-eastern part of Australia. It shows 6- groups of organisms by different colours, and each dot glows so when they are clustered together, they look like a single big dot. It shows how certain groups appear exclusively in coastal areas.
It also features small bar-graphs showing month wise sightings for four popular ones.

**Critique:** The visualisation works well in giving a big picture of diversity and exclusivity of each type of organism. and where it can be seen.

But the data is laid out in just two layers, eliminating the possibilities of having more versatility, even though there are four graphs showing month wise sightings,  it doesn't extend to rest. another visual indicator could be introduced and placed on the map itself which shows what time of a year it would be best to visit. The text in the map only shows popular national parks and places and could be to more branched and detailed so a person living near a place could realise that he can go visit and experience this spectacle.

**Comment by ishaan-nejeeb** [comment]
# Monthly Income of Agricultural Households in India
![128579209_431762544655616_788059099998831080_n](https://user-images.githubusercontent.com/46069650/101223525-3a973a00-36b2-11eb-9596-2b5cdeecbd5c.jpg)
This image shows the state-wise monthly income of agricultural households in India

**Type:** Chloropeth, Declarative and Data-Driven

**Source:** [Data](http://agricoop.gov.in/sites/default/files/agristatglance2018.pdf), [Data Visualization](https://www.instagram.com/p/CITG6qWJZAa/)

**Datatype:** State (Nominal), Monthly Income (Quantitative)

**Visual Encoding:** Text is used to give the name and monthly agricultural income of each state. Hue difference is used to differentiate whether the monthly income is below (red) or above (green) the average (cream). The range is denoted by a color saturation scale

**Critique:** This visualization works well in giving the data at a cursory glance. We are immediately able to discern the states in which the income is below average and which is above and how much. The exact number is also given for each state.
But, this data visualization gives the pure number (the monthly income per state) without giving it any context and factors that affect it. There are things that affect how much the farmer makes like what kind of crops he is selling, how many harvests he makes in a year, how much technology is used in farming. Another factor that affects the sale of crops is whether the farmer is using the mandi system (which guarantees a fairer price) or is he selling directly to third parties. Hence without context like these, it is harder to make meaningful observations from the above data.
