### ISSUE TITLE
Schematic Maps

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#53]
Hi everyone,

As discussed in the class, let’s pick our hometowns and create schematic maps for tourists, or a specific use case. You can see some of the previous maps created on #41, #48, #37 & #27. 

Here are some references to go through:

**Schematic Maps:**

Get inspired by the story behind the most seminal schematic map: [London Underground Map by Harry Beck](https://www.youtube.com/watch?v=Bg3pfUqdLp4), and a critique of the old design along with some interesting alternatives in this [TEDx talk on usability of metro maps](https://www.youtube.com/watch?v=bjPZSmDAyyM).

Closer home, have a look at the [Isometric & Schematic map of the IIT B by Prof. Mandar Rane](https://mrane.com/portfolio/iitb-campus-map/).

Here is the process behind one of my schematic maps: [Andamanese Language Map](http://fortheloveofmaps.tumblr.com/tagged/Andaman/chrono).

A Guardian article featuring animations [transforming schematic maps into geographically accurate representations](https://www.theguardian.com/cities/2017/jun/27/twisted-tracks-metro-maps-real-life-geography-visualised).

A great collection of [schematic maps of most cities around the world](http://www.inat.fr/maps/) created by INAT, like [Delhi](http://www.inat.fr/metro/delhi/) & [Mumbai](http://www.inat.fr/metro/mumbai/).

**Cartography / Map Design:**
[Essays on Digital Cartography](https://www.justinobeirne.com/) by Justin O’Beirne.

[David Rumsey’s huge map collection](https://www.davidrumsey.com/) for some vintage cartography inspiration.

[The Five Elements](https://en.wikipedia.org/wiki/The_Image_of_the_City) for forming a mental model of a city, from [Kevin Lynch’s book The Image of the City](https://mitpress.mit.edu/books/image-city).

**Resources:**
[Maki icon set for using quick icons under CC0 license](https://www.mapbox.com/maki-icons/), do try editing them in the [Maki Editor](https://labs.mapbox.com/maki-icons/editor/) if you want to customize them.

**Comment by mohakgulati99** [comment]
<h1>Vasant Kunj Schematic Map</h1>

![SCHE-10](https://user-images.githubusercontent.com/55638531/90802360-c0c28700-e334-11ea-947e-30c259e3aefe.png)
![SCHE-09](https://user-images.githubusercontent.com/55638531/90802378-c7e99500-e334-11ea-889f-d0f1fd63e157.png)
![SCHE-08](https://user-images.githubusercontent.com/55638531/90803967-2d3e8580-e337-11ea-9064-56f99d1927c7.png)
![SCHE-11](https://user-images.githubusercontent.com/55638531/90949917-b5717780-e46a-11ea-9760-178ade0b5994.png)

![SCHE-12](https://user-images.githubusercontent.com/55638531/90949915-b0142d00-e46a-11ea-9195-82e4978ee939.png)

Most of my markers were forming these small clusters so I decided to just label the overall cluster/group on the map and then give a list of individual restaurants in each cluster below.
![SCHE-13](https://user-images.githubusercontent.com/55638531/90950264-89a3c100-e46d-11ea-914b-1dcf2ec2bb5d.png)

and then I also came up with this accompanying diagram which gives you a zoomed out context on where Vasant Kunj is in Delhi
![SCHE-16](https://user-images.githubusercontent.com/55638531/90935051-090aa380-e420-11ea-8b14-b2d3a7d6429f.png)
![SCHE-14](https://user-images.githubusercontent.com/55638531/90935120-30fa0700-e420-11ea-931d-3113b212775c.png)
(Below) A more formalized version of the info, no colour or type treatment done yet.
![SCHE-15](https://user-images.githubusercontent.com/55638531/90950578-90800300-e470-11ea-85a4-8de80a47a689.png)

![SCHE-17](https://user-images.githubusercontent.com/55638531/90950163-befbdf00-e46c-11ea-9342-515588a9f749.png)

I decided to leave out 'Masoodpur Market' because the 2 places in that cluster we're consistent with the other places in the other clusters

Typography
<hr>

![steps-03](https://user-images.githubusercontent.com/55638531/97473088-94e50280-1970-11eb-8159-3dc2d9fcbc61.png)

Icons
<hr>

![steps-02](https://user-images.githubusercontent.com/55638531/97473097-99a9b680-1970-11eb-81fd-34d6f264616f.png)

Vasant Kunj Geographical Context
<hr>

![steps-04](https://user-images.githubusercontent.com/55638531/97700428-d2ad6c80-1ad1-11eb-9fe3-7ec21196f0a1.png)


VK Schematic Map _Version 1_
<hr>

![Version 1](https://user-images.githubusercontent.com/55638531/99994687-590e5300-2ddf-11eb-82ff-f24ef1ca36c2.png)


Update

![Update-05](https://user-images.githubusercontent.com/55638531/99994025-7e4e9180-2dde-11eb-8c71-9b9695ac21a1.png)

VK Schematic Map V2
<hr>

![VasantKunj_SchematicMap_GithubSize](https://user-images.githubusercontent.com/55638531/99994793-7f33f300-2ddf-11eb-9d6a-709f15df7bd8.png)

**Comment by Niharika-Mohile** [comment]
### Gurgaon Schematic Map // In Progress

![Ggn 2](https://user-images.githubusercontent.com/69865621/90670002-2a2c9200-e270-11ea-9be0-330e0694e902.JPG)
This is the original map of Gurgaon, my hometown, taken from Google Maps

![image](https://user-images.githubusercontent.com/69865621/90670099-50523200-e270-11ea-920d-bb8130d53cf3.png)
I first traced out the map as is, using illustrator

![image](https://user-images.githubusercontent.com/69865621/90671396-47626000-e272-11ea-880b-cde9afdc7308.png)
I then tried to abstract the image, keeping the key features

### Gurgaon, My Home: A Schematic Map

After talking to Rasagy and getting proper feedback, I decided to start from scratch, and do the only the part of Gurgaon I know, the north-eastern part.
![Ggn1](https://user-images.githubusercontent.com/69865621/90866061-f60cba80-e3b0-11ea-8a19-08dafcbfe102.JPG)

I then began to abstract the above map, the part that I know. For the city itself, I chose to go with a shape that's sharp and hard-edged, yet still friendly, like the city itself. It's colour is a sky bluish grey, they very shade the glass buildings outside my home reflect. For natural elements like the scrub forests at the edge and the aravalli hills, I tried using more organic, softer shapes and curves rather than angles. The metro line, though it leans more towards the tech/city aspect as compared to nature, still has curves. This is for two reasons: the metro itself turns through curves, rather than sharp angles. Moreover, in the metro map too, the metro lines don't use sharp angles, they use curves, and I used the same to maintain consistency.
![image](https://user-images.githubusercontent.com/69865621/90868610-ad570080-e3b4-11ea-8b8a-2f9453088c24.png)

I then added to the map the places that I know and frequently visit, like my home, school, local shopping market, the road which has all the malls, etc. Again, to keep in tone with the techy/city aspect of Gurgaon, I used a diamond instead of a circle as the place-marker. This is what I finally up with:
![image](https://user-images.githubusercontent.com/69865621/90869787-581bee80-e3b6-11ea-8090-c3dc141ad1ba.png)

For the final submission, I placed my map in context with the rest of NCR, and added a few important labels
![image](https://user-images.githubusercontent.com/69865621/90905766-45bda700-e3ee-11ea-9cab-64aa44e8dab0.png)

**Comment by NiharikaK1543** [comment]
### **Jaipur Schematic Map- In progress**
![3](https://user-images.githubusercontent.com/60334656/90673531-8645e500-e275-11ea-93f5-ca6686be99fd.png)

I explored open street maps and found that there are two types of boundary for Jaipur: The Tehsil boundary and Jaipur Municipal Corporation Boundary.
As two of the places that I wanted to include in my map was falling out of the Tehsil boundary, I chose to go with the Jaipur Municipal Corporation Boundary which included all the required places from open street maps.
![4](https://user-images.githubusercontent.com/60334656/90689027-0297f280-e28d-11ea-962a-75b4e14ec193.png)
I roughly mapped the roads, gardens, metro line and the historical places and monuments inside the boundary.
![5-01](https://user-images.githubusercontent.com/60334656/90924626-74974580-e40d-11ea-81ce-74ff8af13b0b.png)
Cleaned the map to only the required roads and references and only the national highways on the outside.
![6-02](https://user-images.githubusercontent.com/60334656/90924698-90025080-e40d-11ea-86a5-5c1cc4041296.png)
Going towards abstraction...
![7-05](https://user-images.githubusercontent.com/60334656/90947612-c3b49900-e454-11ea-9753-1b29ab648b6c.png)
I skewed the map horizontally to avoid crowding in the center. Final Form, now working on markers and colors.
![8-06](https://user-images.githubusercontent.com/60334656/90949060-966ee780-e462-11ea-8309-0ec64032e1a1.png)
Final Map with a subtle background color palette and more prominent markers based on the past feedback.
![Final map-01](https://user-images.githubusercontent.com/60334656/101211465-3ca2ce00-369d-11eb-9686-3dccb6d6b6b9.png)

**Comment by kumarrishabh0707** [comment]
# Hazratganj, Lucknow Schematic Map
I planned to chart out the downtown area of Lucknow for my map, where I spent most of my teens exploring around. 
 
![Intro-01](https://user-images.githubusercontent.com/16447438/90700211-dab38980-e2a2-11ea-9c05-668a1efb00eb.png)

I started listing out the places that I wanted to include on the map, majorly eateries and hangouts. 

![Map scribble](https://user-images.githubusercontent.com/16447438/90701900-84951500-e2a7-11ea-8ebf-1fc59fd2d55f.png)

I started mapping out the major roads and the metro line by tracing the map.

![Map with roads and metro](https://user-images.githubusercontent.com/16447438/90704460-2586ce80-e2ae-11ea-8e4c-86431d1db433.png)

![Map scribble with major roads](https://user-images.githubusercontent.com/16447438/90704471-320b2700-e2ae-11ea-8751-90d44fb5e980.png)

I  cleaned up the map a little by putting down some placeholders, so as to not rely on my doodles for the encoding, and added features that cover a larger area like parks, river banks and malls as shapes.

![Map cleanup](https://user-images.githubusercontent.com/16447438/90706132-1e61bf80-e2b2-11ea-8a99-cf8b99ce90b3.png)

![Map cleanup without back-01](https://user-images.githubusercontent.com/16447438/90706715-70571500-e2b3-11ea-92eb-c543890ff64a.png)

I started with the abstraction of the map, by eliminating complex angles and aligning it with the base. The river gives a great reference for the orientation of the map. The colours are placeholders for the time being.

![Final map abstracted progress 5-02](https://user-images.githubusercontent.com/16447438/90935101-25a6db80-e420-11ea-8df2-922814ddb580.png)

I adjusted certain dimensions so as to accommodate more information, and started placing objects of interest with some labelling. I decided to add some iconic roundabouts. 

![Final map abstracted progress 8-02](https://user-images.githubusercontent.com/16447438/90938409-a963c680-e426-11ea-8e27-b37414c6eac0.png)

I adjusted colour tones and saturation so that the schematic can work with black and white printers, but I am still not sold on the colours.

![Final map abstracted progress 10-02](https://user-images.githubusercontent.com/16447438/90941285-50e4f700-e42f-11ea-83fb-664dfdcf8197.png)
![Final map abstracted progress 9-02](https://user-images.githubusercontent.com/16447438/90941287-517d8d80-e42f-11ea-8a39-81da3a97f97f.png)

Edited colours to balance hierarchy and added labels.
![Final map abstracted-02](https://user-images.githubusercontent.com/16447438/99917838-e77bc980-2d38-11eb-91ac-eee787d61c5e.png)

Adjusted colours and added patterns to add some character.
![Final map abstracted color-03-03-03](https://user-images.githubusercontent.com/16447438/100147645-aa8f0e80-2ec1-11eb-9bc9-9ba667de8a3e.png)

Further tuned the aesthetic by adding a paper texture.
![Final map abstracted color-03 smol adjusted 2](https://user-images.githubusercontent.com/16447438/100149137-bd0a4780-2ec3-11eb-95e6-3725261dd2f4.png)

**Comment by rasagy** [comment]
This is great progress everyone! For others, feel free to share where you are as a comment. It’s okay if you’ve gone in a direction where you are stuck or are unhappy with — we’ll look at the comments in the session today and discuss next steps or alternative approaches.

**Comment by praffi2000** [comment]
**_Intent:_** 

A lot of scientists, professors and students visit various Scientific organisations located in/near my hometown from all over the world very frequently. I want to make a schematic map which

1.  Shows easy directions to people visiting within district or state, only showing major turns at required junctions.
2.  Connects each organisation/institute with other,
3.  Shows schools and colleges
4.  connect all this with historical places which are very close to the town. (my hometown Gauribidanur is a historical town in Chikkaballapur district and there is no tourist guide available for my hometown as of now)

![45500](https://user-images.githubusercontent.com/60361539/90717049-31818900-e2cc-11ea-98a6-e689bc4d76ba.jpg)
_1. Showing major key locations_

![IMG-2990](https://user-images.githubusercontent.com/60361539/90717072-46f6b300-e2cc-11ea-945d-780bf3c6052e.jpg)
_2. Showing town connection to other cities_

**Update 1**
![image](https://user-images.githubusercontent.com/60361539/90949064-9f5fb900-e462-11ea-957b-1a32dc52ccb8.png)
I mapped out the locations and route

![image](https://user-images.githubusercontent.com/60361539/90949073-c61def80-e462-11ea-9aed-46728db5b1f8.png)
**Abstracted it into a grid and added labels, while maintaining distance scale.

![image](https://user-images.githubusercontent.com/60361539/90949105-1006d580-e463-11ea-9c36-7b0f9bea1b5e.png)
first schematic map so I can use it as a reference when styling it.

![image](https://user-images.githubusercontent.com/60361539/90949152-a5a26500-e463-11ea-8e59-b8336aae9325.png)

Feedback received: Illustrations and map are not in the same perspective, and realistic illustrations look out of place on the minimal map.

**Update 2**
![image](https://user-images.githubusercontent.com/60361539/100552937-8ad85b80-32b0-11eb-92e7-699778e0f4de.png)
I started drawing in perspective referring to the minimal map, started experiments with some colours and textures.

![image](https://user-images.githubusercontent.com/60361539/100552974-d5f26e80-32b0-11eb-9079-94e5a82cd56f.png)
Finished all illustrations with details and added whole lot of terrain, so people can easily recognise the places and routes, just by looking at the scenary.

### Final Update
Added map essentials- legend, labels etc.

![Prafulla_Final_map](https://user-images.githubusercontent.com/60361539/100553075-86f90900-32b1-11eb-8dcc-d972f5b1455e.jpg)

[click here for high resolution image](https://drive.google.com/file/d/10OJ3z5gx5zg9E89QAOqUaNGnTU5MxXnw/view?usp=sharing)

Thank you

**Comment by itsalwaysatul** [comment]
# VAISHALI, GHAZIABAD

Currently I am residing in Vaishali which is a technically a part of Ghaziabad but has connections closer to Delhi.
![Asset 2](https://user-images.githubusercontent.com/68927529/90717317-f0d63f80-e2cc-11ea-9e7e-5ec32b1fc37d.png)

My part of the town has very little going for it in terms of Landmarks and Large locations.
![Asset 3](https://user-images.githubusercontent.com/68927529/90717323-f59af380-e2cc-11ea-9cf2-5aab0612117b.png)
We are surrounded by giants. with three major cities of India bordering us we do have great connectivity.

![Asset 4](https://user-images.githubusercontent.com/68927529/90717326-f6cc2080-e2cc-11ea-89cf-2ea813dafb9d.png)
The over all shape has nothing special in it.

![Asset 5](https://user-images.githubusercontent.com/68927529/90717327-f764b700-e2cc-11ea-9424-937f387f5e9f.png)
Firstly, I trace the area and plot major landmarks. one observation we can make is that there are many hospitals and malls in my area. Vaishali is also encircled by metro lines, rivers, national highways and roads.

![Asset 6](https://user-images.githubusercontent.com/68927529/90717328-f7fd4d80-e2cc-11ea-82bf-85f9e8df8672.png)
After removing the other information.

![Asset 7](https://user-images.githubusercontent.com/68927529/90717330-f92e7a80-e2cc-11ea-8132-8602b22e111a.png)
The basic shape is reminding me of a web of connections or perhaps walls. Perhaps the best abstraction is to avoid any particular shape. 

**AIM:** My aim is to attract people to Vaishali and the best thing Vaishali can offer is a good residential area. The great connectivity is also something i wish to highlight.  

After seeing what people look for in a residential area i noticed a few points. 
a. first priority is price of residence. 
b. they look for connectivity. 
c. the utilities like schools and hospitals are important too.

The sectors of Vaishali offer a great subdivision and i had the idea of a choropleth style of schematic map.

![Asset 8](https://user-images.githubusercontent.com/68927529/90948451-b1d6f400-e45c-11ea-839a-f2671241e054.png)
After that I added the different sectors of Vaishali  and a grid system emerged.

![Asset 9](https://user-images.githubusercontent.com/68927529/90948454-b4d1e480-e45c-11ea-807c-279c7953a830.png)
I rotated the map counter-clockwise and started with an 45 & 90 degree grid.

![Asset 10](https://user-images.githubusercontent.com/68927529/90948455-b56a7b00-e45c-11ea-82bc-3aef0c2ff423.png)
After tracing the main divisions, outline and roads.

![Asset 11](https://user-images.githubusercontent.com/68927529/90948456-b6031180-e45c-11ea-9eb3-a709e68708f8.png)
This is how the different sectors of Vaishali look like after abstraction. Fortunately they preserve their recognisability.

![Asset 13](https://user-images.githubusercontent.com/68927529/90948458-b69ba800-e45c-11ea-9476-45c313ac91b0.png)
Then i experimented with different color schemes to see which will bring out the best contrast for the property prices.

![Asset 14](https://user-images.githubusercontent.com/68927529/90948459-b7343e80-e45c-11ea-9a9e-72db0bd09196.png)
Then i started to add the different visual hierarchy.

![Asset 15](https://user-images.githubusercontent.com/68927529/90948460-b7343e80-e45c-11ea-8d6b-bc843d5983f3.png)
After the labelling.



![Asset 17](https://user-images.githubusercontent.com/68927529/90949395-61b05f80-e465-11ea-8c64-2840196b5d70.png)
Feedback -
1. Adjust the color hierarchy to make the important markers.
2. Use more of the negative space.
3. Adjust the type hierarchy.


![final](https://user-images.githubusercontent.com/68927529/101290561-1ad65200-3829-11eb-84ae-9c79f44fab5f.png)
Final.

**Comment by SankalpoDas** [comment]
### **SCHEMATIC MAP OF HYDERABAD AND SECUNDERABAD**
![initial map](https://user-images.githubusercontent.com/69919031/90868972-353d0a80-e3b5-11ea-8791-3c70668cc46c.jpg)
This map shows the mentioned areas.




![progress](https://user-images.githubusercontent.com/69919031/90869034-4be36180-e3b5-11ea-9e07-52b76a1b4098.jpg)
Selection of places, road and landmarks which are relevant.




![final map](https://user-images.githubusercontent.com/69919031/90869198-83eaa480-e3b5-11ea-99b5-6b7a4802ac25.jpg)
Final outcome which marks some of my favourite Biryani places.
I have tried to keep the colour palette as relevant to the dish as possible.

![FINAL SCEMATIC MAP](https://user-images.githubusercontent.com/69919031/100108349-b0b8c700-2e90-11eb-8ec6-34c5c1de8939.jpg)
After a session of feedback on the previous schematic map, this is the outcome.
The map includes a few more Biryani places you can enjoy, also this map is a little more instructive that the previous making it easier to navigate to these places.

**Comment by parthob** [comment]
### Island Grounds, Chennai, TN

![image](https://user-images.githubusercontent.com/33090222/90946721-3c175c00-e44d-11ea-81ce-1e14a3285392.png)
Image from Google Maps

The shape of the island intrigued me, and I decided to look through it in greater detail. What struck me most was the number of places of worship on this artificially created plot of land - making pilgrims "walk on water", in a manner of speaking.

![Schematic Map-03](https://user-images.githubusercontent.com/33090222/90947601-aed80580-e454-11ea-9a7c-f77f758c2dc6.jpg)


Having decided on this particular purpose for the schematic, I began exploring the map itself.
![Schematic Map-02](https://user-images.githubusercontent.com/33090222/90947615-cadba700-e454-11ea-94ef-d023a9e1cfad.jpg)


Anna Salai, an arterial road in Chennai, cuts through this Island diagonally, proving the starting point for an octilinear alignment. I began to abstract this shape.

![Schematic Map-07](https://user-images.githubusercontent.com/33090222/90947625-e3e45800-e454-11ea-83b0-1c11d8d2f116.jpg)

![Schematic Map-05](https://user-images.githubusercontent.com/33090222/90947637-f3fc3780-e454-11ea-9357-6ad27c834d77.jpg)

![Schematic Map-04](https://user-images.githubusercontent.com/33090222/90947646-ff4f6300-e454-11ea-8114-452d74059136.jpg)

![Schematic Map-06](https://user-images.githubusercontent.com/33090222/90983803-5a38a580-e58e-11ea-9902-6463012ab580.jpg)

![Schematic Map-08](https://user-images.githubusercontent.com/33090222/94352387-113eaa00-0082-11eb-9e06-6c14359122e4.jpg)

![Schematic Map-09](https://user-images.githubusercontent.com/33090222/94352388-17cd2180-0082-11eb-9c49-1754f99aea4d.jpg)

**Comment by MedhaviParasar** [comment]
For my schematic map, I chose the locality that I grew up in, Koramangala. I wanted to make the map for people who are new to Koramangala, to guide them about the most popular places around.

![IMG_1769](https://user-images.githubusercontent.com/69924281/90948569-c071db00-e45d-11ea-98f8-1974d5fa3292.jpg)
<img width="800" alt="Screenshot 2020-08-22 at 9 57 19 AM" src="https://user-images.githubusercontent.com/69924281/90948586-df706d00-e45d-11ea-9c7c-82b4a8caa806.png">
<img width="846" alt="Screenshot 2020-08-22 at 9 57 38 AM" src="https://user-images.githubusercontent.com/69924281/90948590-eac39880-e45d-11ea-926e-ed9fba7374a6.png">
<img width="579" alt="Screenshot 2020-08-22 at 9 58 10 AM" src="https://user-images.githubusercontent.com/69924281/90948601-fe6eff00-e45d-11ea-9d01-44e7884ceead.png">
<img width="662" alt="Screenshot 2020-08-22 at 9 58 28 AM" src="https://user-images.githubusercontent.com/69924281/90948605-07f86700-e45e-11ea-99ec-b9c6acb6a34d.png">
<img width="1119" alt="Screenshot 2020-08-22 at 9 59 06 AM" src="https://user-images.githubusercontent.com/69924281/90948613-1f375480-e45e-11ea-977e-b19464213259.png">
<img width="803" alt="Screenshot 2020-08-22 at 9 58 46 AM" src="https://user-images.githubusercontent.com/69924281/90948609-15adec80-e45e-11ea-9e78-d956d9a8b6f7.png">
<img width="880" alt="Screenshot 2020-08-22 at 10 01 31 AM" src="https://user-images.githubusercontent.com/69924281/90948647-75a49300-e45e-11ea-931b-7b71e26da0f7.png">
<img width="1384" alt="Screenshot 2020-08-22 at 11 04 14 AM" src="https://user-images.githubusercontent.com/69924281/90949623-4a727180-e467-11ea-9bd2-2aefc7e84e78.png">

Final Map
<img width="1369" alt="Screenshot 2020-08-26 at 8 11 10 PM" src="https://user-images.githubusercontent.com/69924281/91318159-8f383880-e7d8-11ea-8efc-98f06960661b.png">
<img width="340" alt="Screenshot 2020-08-26 at 8 11 27 PM" src="https://user-images.githubusercontent.com/69924281/91318171-9101fc00-e7d8-11ea-930a-6dcec58b93b6.png">

**Comment by jeremyiype** [comment]
# Lungs of Bangalore

I decided on mapping out the two major parks in the heart of Bangalore. These and the Ulsoor lake are some of the most popular outdoor recreation spots in the city. I also wanted to add the spots to which I have a personal connection. These are spots I frequent or have special memories at.


**Step 1:** I started with the overall map on Google maps.

![maps-01](https://user-images.githubusercontent.com/60372569/90957274-24ba8c00-e4aa-11ea-9a9e-a2593632ee2d.png)

**Step 2:** I traced out the relevant spots and roads.

![maps-02](https://user-images.githubusercontent.com/60372569/90957298-47e53b80-e4aa-11ea-863e-ed3dab587101.png)

**Step 3:** I began to simplify the paths and areas of the parks and lakes.

![maps-03](https://user-images.githubusercontent.com/60372569/90957326-83800580-e4aa-11ea-81ca-d947c01cbe74.png)

**Step 4:** I explored a series of simple geometric styles.

![maps-04](https://user-images.githubusercontent.com/60372569/90957410-f4272200-e4aa-11ea-8362-b8b5636d78d4.png)

**Step 5:** I fixed on a diagonal grid and a rectilinear design.

![maps-05](https://user-images.githubusercontent.com/60372569/90957438-1d47b280-e4ab-11ea-9538-676c70c7618e.png)

**Comment by ishaan-nejeeb** [comment]
# Kochi a Schematic Map
***
The way I explored Kochi when I came home for vacations was by going to different Cafes and Restaurant and trying out their food.
So I started by marking my favorite eateries in the map
![1-01](https://user-images.githubusercontent.com/46069650/101267199-35062680-377c-11eb-9727-dee8a0a9d540.png)
I then marked out the main roads and routes. 
![Schematic Map-01](https://user-images.githubusercontent.com/46069650/101267168-fec8a700-377b-11eb-9de6-445aaea7359f.png)
Rotated the map slightly to make sure all lines are either horizontal, vertical or a 45 degree diagonal
![Schematic Map-02](https://user-images.githubusercontent.com/46069650/101267269-e442fd80-377c-11eb-80e7-817af02bfd2b.png)
I converted all routes into straight lines
![Schematic Map-04](https://user-images.githubusercontent.com/46069650/101267306-3a17a580-377d-11eb-993e-186500bb1b23.png)
![Schematic Map-05](https://user-images.githubusercontent.com/46069650/101267308-3e43c300-377d-11eb-8fc0-32f531f43e15.png)
![Schematic Map-06](https://user-images.githubusercontent.com/46069650/101267365-cd50db00-377d-11eb-95fc-2e029a84fc0e.png)
Addedd a background
![bg-07](https://user-images.githubusercontent.com/46069650/101267369-d346bc00-377d-11eb-92f3-a8b981136311.png)
Marked all places
![Labels-07](https://user-images.githubusercontent.com/46069650/101267377-e22d6e80-377d-11eb-8088-f4a93448b55c.png)
Added Legend
![Final-07](https://user-images.githubusercontent.com/46069650/101267378-e8234f80-377d-11eb-94c5-fe3986ca387f.png)
***
## Final
![Final-07](https://user-images.githubusercontent.com/46069650/101267381-f40f1180-377d-11eb-8b69-a2364113b15c.png)
