### ISSUE TITLE
Explorations in QGIS - 1 (assignment)

### ISSUE THREAD

**Issue by pkd2512** [mapschool/cartography#60]
- Make a map of India and states. (Mercator projection)
- Highlight a state (home/residence/other) and a city (residence/capital/other)
- Add graticules (lat-lon) to your map as required.
- Use the datasets from Natural Earth to add some rivers or anything that might be of interest (Explore)
- Add labels and styling as required.

**Comment by vimalav** [comment]
India and states 
![image](https://user-images.githubusercontent.com/21723959/116502341-dda25780-a8d0-11eb-96f5-7b5dde4fdf16.png)

State highlighted and labelled
![image](https://user-images.githubusercontent.com/21723959/116502380-ff9bda00-a8d0-11eb-9e63-b1b5a220aa89.png)

My Assembly Constituency and district borders are highlighted 
![image](https://user-images.githubusercontent.com/21723959/116504616-51932e80-a8d6-11eb-94a5-e61f54e9ba07.png)

Graticules and national highways
![image](https://user-images.githubusercontent.com/21723959/116506074-109d1900-a8da-11eb-8cfb-435b123ab5dc.png)

**Comment by sashacherian** [comment]
![MAP](https://user-images.githubusercontent.com/72463543/116505541-d2532a00-a8d8-11eb-8a2e-3664e79fe19b.png)

**Comment by sashacherian** [comment]
![Uploading MAP.png…]()

**Comment by sashacherian** [comment]
Airports categorised based on the size - medium and large
<img width="1494" alt="Screenshot 2021-04-30 at 11 03 38 AM" src="https://user-images.githubusercontent.com/72463543/116653037-05162480-a9a4-11eb-8908-c296503fb96e.png">


![MAP](https://user-images.githubusercontent.com/72463543/116505669-1c3c1000-a8d9-11eb-81bc-58be746ec828.png)

Himalayas and the Rivers
<img width="1356" alt="Screenshot 2021-04-30 at 7 05 46 PM" src="https://user-images.githubusercontent.com/72463543/116702769-251b0780-a9e7-11eb-84f8-d207d62ed7f2.png">

**Comment by harnehmat** [comment]
<img width="778" alt="Screenshot 2021-04-29 at 10 55 06" src="https://user-images.githubusercontent.com/72489149/116505832-85238800-a8d9-11eb-82ce-08ad49cb84a9.png">

Tried to show:
1. Disputed areas
2. 3 longest rivers
3. 3 largest states
4. 3 largest cities

<img width="1130" alt="Screenshot 2021-04-30 at 09 24 12" src="https://user-images.githubusercontent.com/72489149/116653017-fc255300-a9a3-11eb-8093-cd70e896309e.png">
<img width="1128" alt="Screenshot 2021-04-30 at 09 28 33" src="https://user-images.githubusercontent.com/72489149/116653034-047d8e00-a9a4-11eb-9e60-d4dd3ca1f9be.png">

Showing small, medium and large airports across the states. Tried rule based labelling for large and medium airports and size as per that as well by assigning numeric value to them.
~ The South has more large airports!
~ The largest state does not have any large airports!

**Comment by projectpolymer** [comment]
![image](https://user-images.githubusercontent.com/16228899/116507531-0a5c6c00-a8dd-11eb-90c5-8f0b0b7b039f.png)

Showing:-
1. Disputed borders
2. Rivers in my City
3. State and City
4. Labels

----------------------------------------------------------------------------------------------------------------------------------------------
Airport data:-
![image](https://user-images.githubusercontent.com/16228899/116630259-97043a00-a970-11eb-8276-3f0b237cf5c0.png)


steps taken:-
1. Read CSV file
2. filtered on airports in India
3. filtered on type "closed" and "heliports"
4. converted elevation column, which was read as "qstring" to "double"
5. mapped converted elevation data to the size of the airport points
6. changed the opacity of points to 50% to avoid overlapping
7. Applied filters on labels, for airports where elevation is greater than 1000

**Comment by manjwho** [comment]
Most populated neighbourhoods in bangalore:

![image](https://user-images.githubusercontent.com/67982497/116507755-8a82d180-a8dd-11eb-812e-59f260e317e4.png)
![image](https://user-images.githubusercontent.com/67982497/116507824-ae461780-a8dd-11eb-9503-667c834e4494.png)

Continuing on Bangalore basemap - mapped BBMP schools dataset from Open Cities and tried to practice things we walked through in class:
- Coded markers by to size / colour according to language category
- Used dissolve and clip mask to show only Bangalore Urban Schools
- Imported csv to and joined it to existing attribute table in qgis to attach language, gender, school level data to shape file
- Exported and refine in illustrator (faced lot of issues, very irritating!). Map Composer helped.

![Schools in Blore - by Language - 2013-01](https://user-images.githubusercontent.com/67982497/116652926-ced8a500-a9a3-11eb-8031-fd087f30b10c.jpg)

Visit this link for [process screenshots](https://www.notion.so/Adventures-in-QGIS-18a923db322d4d20a7cf4205859ee375).

Feedback:
1. Cannot make certain categories' markers larger than others because the data is uni dimentional. Try to find some other way to make those schools visible, eg. tie it to number of children in each school (find this data!)
2. Purple base-map is creating lot of noise. Try something more subtle to make the data show up better
3. Have annotations with few insights to handhold the reader through the map reading. Even if they aren't able to make sense of the chart, they can still make out what you are trying to show.
4. Stacked bar chart is fine but the columns are not clear. Try it has horizontal bars with clearer labels. No need to add language labels since the legend is on top. 
5. Avoid tilted labels! 
6. Incorporate scale for city level maps. Can also include a locator map according to the audience of where Bangalore is. (Country / World map)
7. Mention the data sources!

**Comment by Rajshree0111** [comment]
## Exploration!

Refined on Illustrator
Showcasing:
- Districts, states, and country boundaries with various stroke weights and types. 
- Disputed area
- Special attention to 2 districts - Banglore and Gautam Budh Nagar

![hello world-01](https://user-images.githubusercontent.com/72490856/116631690-21e63400-a973-11eb-9a18-c0313861db78.jpg)

Problem faced:
Unable to label the specific districts on QGIS (Banglore and Gautam Budh Nagar in this case)

**Comment by Bhanvee** [comment]
Explorations (assignment and jamboard)!

1. Assignment
- Figuring out the national borders (India Map)
- Highlighting states and their names/labels
- Highlighting my birth-state (Maharashtra) 
- And birth-town (Nagpur, Vidarbha district) area over the state
- Exploring graticules and roadways over these all.

![1](https://user-images.githubusercontent.com/11972623/120930952-225db180-c70d-11eb-8072-c64f583b82a6.png)
![2](https://user-images.githubusercontent.com/11972623/120930961-27bafc00-c70d-11eb-99b0-50e2431398fc.png)
![2a](https://user-images.githubusercontent.com/11972623/120930965-2be71980-c70d-11eb-8b29-af89f23acbde.png)
![3](https://user-images.githubusercontent.com/11972623/120930967-2e497380-c70d-11eb-8626-4afe52332f0f.png)
![3a](https://user-images.githubusercontent.com/11972623/120930968-2f7aa080-c70d-11eb-9d21-16a4c56e9272.png)
![4](https://user-images.githubusercontent.com/11972623/120930969-30133700-c70d-11eb-91fb-c191a774a601.png)

2. Jamboard explorations

![Jamboard 2](https://user-images.githubusercontent.com/11972623/120931079-aca61580-c70d-11eb-9b81-05edf79b4a0b.png)
![Jamboard 3](https://user-images.githubusercontent.com/11972623/120931083-afa10600-c70d-11eb-8fdb-c5cb51d4d957.png)
![Jamboard 5](https://user-images.githubusercontent.com/11972623/120931085-b16ac980-c70d-11eb-8b19-238f05f6b8f1.png)
![Jamboard 1](https://user-images.githubusercontent.com/11972623/120931087-b29bf680-c70d-11eb-86fe-dcb9b0d85235.jpg)

**Comment by arunkumaryes** [comment]
**QGIS Exploration**

- Loaded map data and added a OSM background

![SS](https://user-images.githubusercontent.com/38319420/122341953-ad3a7980-cf61-11eb-81ad-271c922b3161.png)

- Imported district view and played around with color depths

![Screenshot 2021-06-12 180349](https://user-images.githubusercontent.com/38319420/122341961-b0ce0080-cf61-11eb-8783-a7d604c2e15e.png)

- Labeled and Formatted the map, made it printable at A4 scale

![map](https://user-images.githubusercontent.com/38319420/122341975-b4618780-cf61-11eb-8cd0-bffaf7a8d6f3.png)

- Made a small data viz of nuclear power plants in Indian and their capacities

![pr](https://user-images.githubusercontent.com/38319420/122341993-b75c7800-cf61-11eb-92e8-c8579c1f5c80.png)

**Comment by rasagy** [comment]
This was great to see! Thanks @pkd2512 for documenting this in issues. Closing this now.
