### ISSUE TITLE
#1 Cartography inspiration

### ISSUE THREAD

**Issue by rasagy** [mapschool/cartography#64]
Hi everyone,

Add a comment to share maps by a specific cartographer/graphic designer that you’ve found interesting. Feel free to add some context for others, like:

- Who designed the map (era/background)?
- What type of map(s) is it? (Geographical/Political/Physical/Topographical/Climate/Schematic/Fantasy/Illustrative)
- What details did you notice in the design?

For example, we looked at [Eduard Imhof](https://www.atlasofplaces.com/cartography/kartograph-und-kuenstler/), a Swiss Cartographer whose hillshading approach is something I’ve always been inspired by. You can also explore other artists mentioned in the books in the KMC, like the illustrative work by [relajaelcoco studio](https://www.behance.net/gallery/10640671/Goods-of-Spain-map), [Stuart Hill](https://www.behance.net/Stuart_Hill) & [Jenni Sparks](https://www.behance.net/gallery/22552047/Moving-Mountains-Map). You can also explore [my Pinterest board](https://in.pinterest.com/rasagy/for-the-love-of-maps/).

**Comment by someshsahoo** [comment]
![EHW_Introductory_Map](https://user-images.githubusercontent.com/93121881/157180144-cabf3849-9041-4753-9f5e-7c0c925d174c.jpeg)
**Locations and Wanderings of the Aboriginal Tribes.**
_The map shows the settlement and movement patterns of pilgrims and the migrations of Native American Tribes in the Eastern U.S.._

### About Emma H. Willard
- The map was designed by **Emma Hart Willard**, 19th-century cartographer, historian, information visualiser, educator, and women’s rights activist.
- Willard grew up in an era when girls were barred from formal education beyond primary school. In her long life, far exceeding her generation’s life expectancy, she went on to become a pioneering educator, founding the first women’s higher education institution in the United States.
- Willard understood that improving the future requires a robust understanding of the past, so that one may become an informed, engaged, and effective agent of change in the present.


### Design Philosophy
She advocated a localized approach to learning one’s land, contrary to the era’s common practice: **“Instead of commencing the study of maps with the map of the world, which is the most difficult to understand, the pupil here begins, in the most simple manner imaginable, to draw a map of his own town.”** 

- It is a **Geographical map** with accurate representation of the movement and settlement patterns. Along with this, it shows lakes and rivers (flowing water bodies as one of the information layers). This was the first printed map to document the migrations over time. 

### Emma's style in Cartography
1. Use of colours to depict different Native American Tribes.
2. Use of vectors (arrows) to show the movement pattern of pilgrims and the migrations of Native American Tribes instead of connecting from one place to the other, giving a better understanding of history of America at a local scale.

> These were unprecedented visual strategy for mapping American history that re-conceptualized the **past on a plane rather than in a narrative. It was an innovative effort to visualize movement in a spatial map.**


### Details noticed

1. Prominently shows how the settlements and movements have followed the routes along the rivers and concentrating in towards the north Eastern part of America.
![EHW_Introductory_Mapnorth americ](https://user-images.githubusercontent.com/93121881/157184589-40646bd7-ffa3-4471-9b32-44e4731e7073.jpeg)

2. Shows how different tribes were at same location and then moved to different parts of America (Red & Green near Ohio river). 
![EHW_Introductory_Mapohio](https://user-images.githubusercontent.com/93121881/157184293-2732e74c-fe63-41ab-a91f-6ba84ee0368e.jpeg)

3. Differentiates lands and Water bodies by drawing of concentric contours.
![EHW_Introductory_Map](https://user-images.githubusercontent.com/93121881/157184152-4975b525-e93b-4d4e-9883-3d86e2e566cf.jpeg)


### Key takeaways

1. Minimalistic approach towards representation of information.
2. Amount and quantity of information presented and the layers of information.
3. Cater to the target audience- It was shown as the introductory map which students see first and absorb. Keeping it small scale and localised helped audience known more about the geography and then expand from there.
4. Use of elements like lines and organic contours to differentiate entities like land, water bodies, shores etc.

**Comment by SudevKiyada** [comment]
# Dr. Harold Norman Fisk

![fisk01](https://user-images.githubusercontent.com/44196782/157264961-f6651e86-138f-456c-98f2-62e52092d3a4.jpg)

"The Mississippi River Meander Maps" is a series of topographic maps created by Harold Fisk, a cartographer for the Army Corp of Engineers. The map encompasses a unique depiction of Mississippi river in a sense that only one map is enough to understand the history of the river. It shows the snake-like bends and oxbow lakes (U shaped water bodies formed because of bends) at various stages throughput the history.

### What I like about the map
- Unique way of consolidating huge information
- Colors used to make the river and it's stages stand out even with the presence of other elements
- The sheer amount of details !

### Other inspirations
I wasn't satisfied with just Meandering Maps and so I spent considerable time browsing through various other cartographer's and designer's work. I made a [quick prototype](https://www.figma.com/proto/cudD8BkUGtLSiYgTT0QiDg/Cartography-inspiration?page-id=0%3A1&node-id=5%3A72&viewport=305%2C48%2C0.57&scaling=scale-down) to show other inspirational maps.

**Comment by Tej333** [comment]
Thejashwini D 

1. Who designed the map ?
Marian Bantjes is a designer, typographer, writer and illustrator working internationally from her base on a small island off the west coast of Canada, near Vancouver. 

2. Isle of Knowledge is a beautifully illustrated map of "the 'known' beyond which lie monsters," created for the second installment in Bantjes's column for U.K. illustration magazine [Varoom](http://www.varoom-mag.com/webonly/index.html) on the theme of "Knowledge."

![image](https://user-images.githubusercontent.com/36147802/157288172-ca2d4875-9c4b-4548-9ffa-75a6a85036ae.png)

![image](https://user-images.githubusercontent.com/36147802/157288219-812d28bf-fe81-4129-9516-9e9dc95bd774.png)

![image](https://user-images.githubusercontent.com/36147802/157288275-46619204-b9ce-46bd-b21b-66b0baedfc54.png)

![image](https://user-images.githubusercontent.com/36147802/157288299-a09594ef-5e7e-4502-814b-cd487bfcc82f.png)

4. What I like about the map
It is a beautiful interpretation of the human condition 
Use of texture to show depth 
Mental model of the unknown

**Comment by ginaphil** [comment]
# Emily Garfield

![Group 4](https://user-images.githubusercontent.com/32394598/157297568-21e80860-46e7-4ef1-aae4-63a34a4dd9fb.png)


Emily Garfield, from the **_current era_**, creates intricate maps of imaginary places that explore the origins of cities and the function of maps themselves. The maps as very aesthetic, artsy and uses the brain's ability to respond to art and aesthetic beauty.

> **"My drawings don't describe real places. But people still identify them as maps right away."**
> 

Her maps, while being imaginary combine both and **_illustrative and topographical map style_**. The topography of watercolor paper, the force of gravity on ink, or the tensile limitations of paper all structure her drawings in the same way that a landscape influences urban growth.

**Imaginary Cartography**

Her intricate pen and watercolor drawings are inspired by the visual language of maps, as well as the fractal similarity that cities share with biological processes such as the patterns of cells and neurons.  She invents each place as she draws, thinking about the clustering of neighborhoods, patterns of roads, and the individual selective memory that an inhabitant would use to navigate their city. 

**Details**


![Group 6](https://user-images.githubusercontent.com/32394598/157300137-b1b49398-bd50-4cfd-9639-a624d96de699.png)

![Group 8](https://user-images.githubusercontent.com/32394598/157303022-0a9736be-9523-4335-86bc-15d9fc0cf7e4.png)

![Group 7](https://user-images.githubusercontent.com/32394598/157302590-5d5a24a6-7277-415d-89a5-8b80aa4cc3cd.png)

# Lienke Raben

## **Great Places of Amsterdam map**


![037d65f6-1985-418a-b6c9-a61bedbddf7d_rw_1920](https://user-images.githubusercontent.com/32394598/157313626-3e46d17e-47e0-40b3-96ee-d92f8683c4c1.jpg)

**Year:** 2016

**Type:** Illustrative

**Details:**

![Group 9](https://user-images.githubusercontent.com/32394598/157315270-d92d213b-b900-4134-a787-a2eb267b6872.png)

**Comment by aashibhaiji** [comment]
### **Cartography Inspiration**

(Still reading up on some old maps, will add to this thread)

Looking at maps from the different aspects of design : Layout, Composition, Geometric Shapes, Patterns, Transparency, Strokes, Lines, Typography, Legend, Labelling, Visual Hierarchy, Symbols and Markers, Illustrations, Colour Palette, Title.

**Migratory Birds Map**
https://www.behance.net/gallery/129181901/Mapa-de-Aves-Migratorias-Migratory-birds-Map
<img width="521" alt="Screenshot 2022-03-09 at 8 07 15 AM" src="https://user-images.githubusercontent.com/93115145/157368159-80d88ae1-939b-4fb0-8654-8f644b3f03aa.png">



**Illustrations for an Inflight Magazine**
https://www.behance.net/gallery/92254037/Map-illustrations-for-inflight-magazine

<img width="1052" alt="Screenshot 2022-03-09 at 9 05 44 AM" src="https://user-images.githubusercontent.com/93115145/157367947-cc3eccc0-c368-42c3-9397-68dc6ab99345.png">



**The city of seven hills**
https://www.behance.net/gallery/94443031/Plovdiv-CIty-Branding-02

<img width="377" alt="Screenshot 2022-03-09 at 12 53 52 AM" src="https://user-images.githubusercontent.com/93115145/157363958-6a08e928-b129-4f0a-9617-712c90be3cef.png">

**Natural Dyes of Our World**
https://www.behance.net/gallery/56177195/Natural-Dyes-ofOur-World

<img width="1051" alt="Screenshot 2022-03-09 at 12 39 59 AM" src="https://user-images.githubusercontent.com/93115145/157363929-434157b0-b993-4a76-af1a-4180733f7ffe.png">

**Ornate Cartography : City of Liverpool**
https://www.behance.net/gallery/128356639/The-City-of-Liverpool-Ornate-Cartography

<img width="606" alt="Screenshot 2022-03-09 at 12 25 43 AM" src="https://user-images.githubusercontent.com/93115145/157363920-a1783489-4f4b-413f-a530-bf35d62bc235.png">

**Way Finding and Identity**
https://www.behance.net/gallery/74989609/City-Guide-Wayfinding-and-Visual-Identity-for-Toender

<img width="805" alt="Screenshot 2022-03-09 at 12 46 28 AM" src="https://user-images.githubusercontent.com/93115145/157363940-7e4921a7-523a-48c6-9ddb-f2ca3edf6e4a.png">

<img width="1228" alt="Screenshot 2022-03-09 at 12 50 52 AM" src="https://user-images.githubusercontent.com/93115145/157363948-8a7d5ab6-7fcb-44c9-852b-4921a65b9f09.png">

<img width="630" alt="Screenshot 2022-03-09 at 12 59 17 AM" src="https://user-images.githubusercontent.com/93115145/157363962-dc8266eb-1cb8-4140-aaa9-ff404436e11c.png">

**Comment by chickensoup28** [comment]
# Map of the sky by Dutch cartographer Frederik de Wit.
![1024px-Planisphæri_cœleste](https://user-images.githubusercontent.com/93116394/157364488-06371e77-1011-4f24-ac71-aca1a6533f6b.jpg)
![1024px-De_Wit_1670_Southern_hemisphere](https://user-images.githubusercontent.com/93116394/157364818-a36d2472-43ce-4c43-8c2a-bf19d32a5cb9.png)

- Designed by Frederik De Wit ub tge 17th century (1670)
- It is a hand drawn star chart (88 constellations) created with illustrations of mythological creatures 
- It shows solar orbits and lunar phases and maps the constellations visible from Earth with illustrations

## Some details of the map are as follows: 

![48889a2ef3c00cb219_Screen Shot 2016-04-08 at 1 46 19 PM](https://user-images.githubusercontent.com/93116394/157365844-688d4e1d-6a16-4dee-99d4-4193b193dcb8.png)
The horse in the illustration here is Pegasus (A mythical creature). It is generally white in color but Federick decided to add colors to the wings.The constellation named for the winged stallion was one of the 48 listed by Ptolemy in the 2nd century AD.

![c76b532803eb1c9e11_Screen Shot 2016-04-08 at 2 01 15 PM](https://user-images.githubusercontent.com/93116394/157366095-78d5ce97-7758-49cf-a833-3b2ac8c6a1a6.png)
The upside down puppy is the brightest star in the Earth's night sky, Sirius and is derived from the phrase "dog days of summer." 

![fc7d40fa98a449afc8_Screen Shot 2016-04-08 at 2 22 59 PM](https://user-images.githubusercontent.com/93116394/157366263-69567f76-1f4d-44ad-b2a8-994761643f20.png)
Finally between Pisces and Aries the figure is of an enormous sea monster known as Cetus (a mammal fish hybrid derived from the Greek mythology)

**Comment by Talphi** [comment]
https://fullermaps.com/print-shop/bristol-blues

![image](https://user-images.githubusercontent.com/93115371/157374969-92cdf333-1409-474a-b8d8-d0b2035adaae.png)

![image](https://user-images.githubusercontent.com/93115371/157375306-4774f4f5-b231-42de-b353-787682e4bc86.png)
![image](https://user-images.githubusercontent.com/93115371/157375379-6d20b155-7e52-4438-8551-531e54a1162f.png)
Detail from Antonio Garcia Cubas, ["Cuadro historico-geroglifico de la peregrinacion de las tribus Aztecas que poblaron el Valle de Mexico. Num. I,"](https://searchworks.stanford.edu/view/wb420zq7222) 1858. David Rumsey Map Collection, David Rumsey Map Center, Stanford Libraries.


Maps by my friend Abhranil Munsi Maps

![Screenshot_20220309-102823 (1)](https://user-images.githubusercontent.com/93115371/157376173-358c62ba-8533-46a1-a42b-eab7d80dd84a.jpg)
![Screenshot_20220309-102833](https://user-images.githubusercontent.com/93115371/157376176-7fa7031a-d50b-4579-8bb7-75a805363667.jpg)
![ny-ramen-map-all-you-can-eat-press (1)](https://user-images.githubusercontent.com/93115371/157378324-30c12f51-8b12-4a13-88c0-f5962d900b64.jpg)
![tumblr_inline_oaglrwMUOA1qai5m3_540](https://user-images.githubusercontent.com/93115371/157378326-83b7fd83-c3ba-4e42-bf28-989b012f45d1.jpg)
![tumblr_inline_oaglryc3vQ1qai5m3_540](https://user-images.githubusercontent.com/93115371/157378327-b920f373-f4b1-4aed-9014-959fb8388fdb.jpg)
![5f6cf07872053 560b3222eb709](https://user-images.githubusercontent.com/93115371/157378329-6690ee67-eaae-485c-92db-81606447f1e7.jpg)
 


Food Maps
![AllYouCanEatPress_DoughnutMap_Open](https://user-images.githubusercontent.com/93115371/157378316-0b08ea33-9659-4a54-8ec6-f18db68dfd6c.jpeg)
![croissant-map-inside](https://user-images.githubusercontent.com/93115371/157378321-4df5fbbd-6893-448d-876c-0150e9368902.jpg)
![059de780ad3ff310157b3aca09db339e](https://user-images.githubusercontent.com/93115371/157378674-8ddba4b3-5010-4db3-bf65-f072bc869b82.jpg)
![e0ba7368fe19ab059ed6b02e1c08ce1b](https://user-images.githubusercontent.com/93115371/157378679-7ae418d0-7b23-41ce-b8a9-80bd28189c85.jpg)
![9f3e93c4dc381a83dae9b6370769f599](https://user-images.githubusercontent.com/93115371/157378681-3a37e364-7a20-45ed-8a6d-8da076e4168d.jpg)
![52c3abe4fcd9ed86a536639ef08b0bfd](https://user-images.githubusercontent.com/93115371/157378683-050a304b-e636-4158-86d5-0c3626fde462.jpg)

**Comment by Abhimanyu-Saha** [comment]
![Screenshot 2022-03-10 080947](https://user-images.githubusercontent.com/80443134/157577942-0d79bea1-8059-408a-a966-2044eb75ba98.png)
Alex Foster is an illustrator based in UK. He specializes in map Illustration. 
https://www.alex-foster.com/

**Design Philosophy:**
1.  His map combined with the illustration connects deep to the audience and goes beyond the conventional way we use maps. The illustrations help connect and build a memory of the place which goes beyond the primary navigational or informative purpose.
![8fe24076304245 5c657a5571629](https://user-images.githubusercontent.com/80443134/157578664-64b5e110-c766-4bec-bb0f-95420c9785da.jpg)
Craft Beer Map of Indianapolis

![Screenshot 2022-03-10 083527](https://user-images.githubusercontent.com/80443134/157580676-6b63db0b-e8f0-4222-9f95-28636d1b4702.png)
Story Maps by Embroidery(Kantha Stitch) -------Ekta Kaul

Ekta Kaul is an award-winning Textile Artist based in London and alumni of NID (Ahmedabad). She creates embroidered story maps rooted in narrative and textiles that celebrate contemporary, pared-down aesthetics and focus on timeless simplicity.
![Untitled_Panorama-1](https://user-images.githubusercontent.com/80443134/157581636-d058d84f-eb13-407e-a8a3-044cae145739.png)

**Comment by Nivia-J** [comment]
### **Gareth Wood aka Fuller**
Fuller drafts impressionistic “mind maps” of places where he has lived. “I’m making a collection of cartographical love letters,” he says. This hyper-detailed, ink-drawn map is of central London. It contains the personal experiences of the artist, hidden stories, curiosities and factoids. The piece was started in 2005, archived in 2007, and drawing resumed in 2015. This jump creates a change in style and technique. It highlights the progress within the metropolis and the artist himself.

![image](https://user-images.githubusercontent.com/93118546/157800118-a36102a6-cde8-4169-b793-3b778d8f8192.png)

![image](https://user-images.githubusercontent.com/93118546/157800295-887fa269-d6b2-4c53-b433-e45283dc12e2.png)

![image](https://user-images.githubusercontent.com/93118546/157800577-cb156778-60de-4d97-9ca6-51c62f291463.png)

<br> <br> <br> <br>

https://in.pinterest.com/pin/44191640084910025/
![image](https://user-images.githubusercontent.com/93118546/157800787-b6fc0c92-355c-42c4-b19b-15514a90d084.png)

<br> <br> <br> <br>
https://edition.cnn.com/style/article/cartography-in-the-21st-century/index.html
![image](https://user-images.githubusercontent.com/93118546/157801402-a5ec9e06-44d5-41a0-ad53-114fe7e220ac.png)


<br> <br> <br> <be>
Came across this interesting project
https://colouringlondon.org/
![image](https://user-images.githubusercontent.com/93118546/157802211-41ce0034-84ac-41ce-b41d-c6afbabc4516.png)

**Comment by rasagy** [comment]
Thanks everyone for sharing all these inspiring examples! Closing this issue.
