### ISSUE TITLE
QGIS explorations

### ISSUE THREAD

**Issue by pkd2512** [mapschool/cartography#74]
As we go on learning how to work with spatial data in QGIS, drop in your explorations in this thread.

Write a brief description of what your map shows and the data sources used.
Post map screenshots from QGIS showing WIP and final results.

[**Lecture notes**](https://bit.ly/qgis-carto)

### Airports (purple), Ports (blue), Stations (yellow) sized by altitude
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/7580745/217310140-3e9065a0-6aab-4aea-bed5-853ff873b521.png">

### Oil pipelines by volume
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/7580745/217503752-8a2f3588-e489-4a89-9264-23e3b2b89c80.png">

**Comment by 8PocketElf** [comment]
[12.pdf](https://github.com/mapschool/course/files/10673081/12.pdf)

**Comment by 8PocketElf** [comment]
<img width="600" alt="Screenshot 2023-02-07 at 2 14 45 PM" src="https://user-images.githubusercontent.com/111482797/217195651-e2da1b09-0ead-4af6-a045-ea111e638fdc.png">
<img width="952" alt="Screenshot 2023-02-07 at 2 15 10 PM" src="https://user-images.githubusercontent.com/111482797/217195707-13b44df2-c3dc-42c3-bf89-29eccbd9c054.png">
<img width="952" alt="Screenshot 2023-02-07 at 2 15 17 PM" src="https://user-images.githubusercontent.com/111482797/217195736-a7229722-4ab3-40a3-8f6e-b04c324b9d6a.png">

<img width="990" alt="Screenshot 2023-02-07 at 2 58 52 PM" src="https://user-images.githubusercontent.com/111482797/217208913-ef8c7ed8-627a-48c3-bec0-ea03e100d9fa.png">

## co- siesmic landslides in sikkim due to dams 

data layers -
teesta river & its tributaries
major road networks
hillshade
glaciers
glacier lake changes
exisiting dams
proposed dams
protected forest area
earthquakes since 1990s
effected villages due to nepal- india earthquake 2011
landslides cause within 2 days of earthquake

![a11](https://user-images.githubusercontent.com/111482797/226191539-9f344288-b8df-47fa-8d10-0ef254e04a62.png)

work to be done
detailed hillshade
layer by layer data reveal
poster
data narrative, texts & images

![thematic - sikkim earthquake   dams_Page_1](https://github.com/mapschool/course/assets/111482797/41256266-a992-4037-8430-5363414374bc)
![thematic - sikkim earthquake   dams_Page_2](https://github.com/mapschool/course/assets/111482797/fb728985-e0ad-4bbc-a3bb-d26c67fd17fa)

![thematic - sikkim earthquake   dams_Page_3](https://github.com/mapschool/course/assets/111482797/ab2b55f3-a3cd-4d4c-bff8-a4f10a4b8fe4)

![thematic - sikkim earthquake   dams_Page_4](https://github.com/mapschool/course/assets/111482797/e9cdffb2-de66-47dc-aff3-564bc912cb76)

![thematic - sikkim earthquake   dams_Page_6](https://github.com/mapschool/course/assets/111482797/6805405f-5bbf-4f30-a4cb-a9672fa86ca3)
![thematic - sikkim earthquake   dams_Page_7](https://github.com/mapschool/course/assets/111482797/4b101afe-d820-458b-86c0-b54966bfaf99)

![thematic - sikkim earthquake   dams_Page_8](https://github.com/mapschool/course/assets/111482797/92d659e0-da3d-4e32-852e-adb775004d84)

**Comment by mohnishlandge** [comment]
# RGB
![Screenshot (119)](https://user-images.githubusercontent.com/60274031/217710295-51e41784-11c5-497f-b88d-d631fde79204.png)

# Airports
![Screenshot (120)](https://user-images.githubusercontent.com/60274031/217710339-2664aa41-eeae-4c33-92ed-4ca56879bfb4.png)

![Screenshot (122)](https://user-images.githubusercontent.com/60274031/217710412-1b8202f2-a145-495f-8c2d-daed137d663a.png)

![Screenshot (125)](https://user-images.githubusercontent.com/60274031/217710427-e52a758f-89e8-4ad3-b5f3-b706ea088c49.png)

# Rivers - India
![Screenshot (121)](https://user-images.githubusercontent.com/60274031/217710389-db373132-010a-4736-bc73-0759c59bf0b1.png)


# Processing
![Screenshot (123)](https://user-images.githubusercontent.com/60274031/217710476-65ea790b-b523-44a9-8f61-a9dbff1e3a46.png)



# Earthquakes
![Screenshot (126)](https://user-images.githubusercontent.com/60274031/217709884-fbe62bc2-1c2b-443e-9bb5-2b7f7d9ab7a8.png)
![earthquake](https://user-images.githubusercontent.com/60274031/217726081-928cfe26-354d-405f-92ce-94176e6857c1.png)

# Narrative Cartography
![Poster - atomicindia](https://github.com/mapschool/course/assets/60274031/f968509c-1e0f-48b5-a796-87206839ac36)
![Screenshot of documentation website](https://github.com/mapschool/course/assets/60274031/4dfddbf9-5405-4e9a-815d-572b195b7afe)
![Screenshot interactive storytelling of all nuclear powerplants in india](https://github.com/mapschool/course/assets/60274031/746af5d7-d0e4-468d-ae6d-1f4be7653c06)

**Comment by karthikeya-gs07** [comment]
# QGIS Explorations 
Karthikeya GS
___
### Rule-based sectioning in map
![Sectioning of map](https://user-images.githubusercontent.com/39125026/217406966-11b1ce58-a321-4614-b74c-afdbc7ed7ce2.png)
___
### Assigning colours from CSV file to Countries
![Random Colouring to Countries](https://user-images.githubusercontent.com/39125026/217407047-07c3a94b-50a9-4b05-ae29-1c3ad377537c.png)
___
### Population Mapping of the World
![Population Spread](https://user-images.githubusercontent.com/39125026/217407107-195eb3dc-2a2c-4e8d-8fe4-b68f9fc9c628.png)
___
### GDP Mapping of the World
![GDP Spread](https://user-images.githubusercontent.com/39125026/217407142-026c2231-07bb-43cf-a5de-3ffd6eb114e6.png)
___
### Airports of the World - Mapping Elevation as Symbol Area
![Airports and Ports by altitude](https://user-images.githubusercontent.com/39125026/217407226-ac46c04e-0fc8-4648-a627-be82725083bb.png)
___

## India Map Explorations
![India Map - exploration](https://user-images.githubusercontent.com/39125026/217407274-14ce6b13-77e3-4368-9d32-dbc99ad2b305.png)

First Iteration:

![India - Playas Glaciers and Rivers](https://user-images.githubusercontent.com/39125026/217407313-0dcbec22-4914-4069-ab34-67543f4e148d.png)
![India - Playas Glaciers and Rivers – 1](https://user-images.githubusercontent.com/39125026/217408082-9a6f9822-0497-47e3-a4dd-bc671c6e8d6d.png)

Note: Will make India POV soon
___

#### Indian Coastal Water Control
Using reprojection to 44N - for meter projection.
Using line buffer with 'difference' to obtain outer boundaries.

![India Controlled Water Region](https://user-images.githubusercontent.com/39125026/217688328-4dadd9d4-6ecf-456e-b924-f347a8735266.png)
___

### Indian Airports and Connections
Using 'Join by lines (hub lines)' with source and destination airports on separate CSV and common ID values.

![Airport connections of India](https://user-images.githubusercontent.com/39125026/217688761-fa6c05bc-ed78-4211-b329-aa917fa05dd3.png)
___

### World Gas Pipelines with Volume Encoding
Using WKT file with 'Linestring' for the route.

![Wolrd Oil Channels](https://user-images.githubusercontent.com/39125026/217688909-be5a5328-5ca3-4700-9b90-847df2462ec4.png)
___

## World Earthquakes - Last 30 Days (9th Jan - 9th Feb 2023)

### World Earthquakes Map
![Artboard – 1](https://user-images.githubusercontent.com/39125026/217704289-0e18b29f-6f50-4a5a-80c3-1567c45fa55d.png)
___

### Pacific Ring of Fire
![Artboard – 3](https://user-images.githubusercontent.com/39125026/217704397-5cca0b52-28a2-4d2a-bad3-2166cfe16e4d.png)
![Artboard – 2](https://user-images.githubusercontent.com/39125026/217704407-38279134-e23a-45b6-9bf9-3d1945095b62.png)
___

### Major Countries
![Artboard – 4](https://user-images.githubusercontent.com/39125026/217704520-9327af8d-797e-4579-82bc-e390ca440fbd.png)
![Artboard – 5](https://user-images.githubusercontent.com/39125026/217704536-1dbe6adc-4712-4cae-b733-175f258b6b03.png)
![Artboard – 6](https://user-images.githubusercontent.com/39125026/217704549-87c1fb09-7296-44c6-b1fb-f2ecc93e1d20.png)

___

#Schematic Cartography

'East Coast' is a schematic map of all the marine accidents that have happened between the years 2000 - 2015 on the east coast of the US. The map highlights the types of ships that met with an accident wrt the geographical landscape. The map also emphasises the Mississippi River, which is the heartline of trade in the US. 

An interactive version of the map was also made to derive better insights from the map about types of incidents (accidents), and what geographical landscapes could cause such issues.

 
![East Coast - Large Markers](https://github.com/mapschool/course/assets/39125026/7b116ecc-1e66-42ee-ae2b-4ea2a86a6d6a)


### Interactive Prototype
Link - https://xd.adobe.com/view/4d2b5909-5139-449a-9477-c56bc6fa1d67-1878/?fullscreen

![East Coast - Interactive Mockup](https://github.com/mapschool/course/assets/39125026/9445e08e-0d0b-4a1e-b362-791ccb617ab7)

**Comment by amandeep2496** [comment]
![India-and-rivers_2](https://user-images.githubusercontent.com/90832949/217433112-62aa61b9-0e47-4bcb-924e-066bb3230f34.jpg)
![India-and-rivers_1](https://user-images.githubusercontent.com/90832949/217433122-8da44f9f-5617-4101-badf-269c8fc3c707.jpg)
![IndiaAirportClipped](https://user-images.githubusercontent.com/90832949/217448249-f6796761-9ce8-42fe-98a3-b9aadb8362bb.png)
![IndianCoastlineBuffer](https://user-images.githubusercontent.com/90832949/217456195-8a2a586f-99f8-405d-9490-93daefb7d461.png)
![pipeline](https://user-images.githubusercontent.com/90832949/217506278-15f98640-69a5-41f5-8599-2c3fe453808f.png)

**Comment by ParvathyRaju98** [comment]
## Homework 1: Rivers of India
_Version 1_

![Rivers of India](https://user-images.githubusercontent.com/111482857/217434683-58bcbe2b-b8cb-4ce9-b35c-55fdd75330fc.jpg)

**Feedback**

- Outline of the country need not be this thick, demarkation is already obvious
- Fade out the Lat Long lines to make it look like Graph Sheet
- Legend is redundant
- Check Spelling for typo
- River lines & State Lines are overlapping and there is no hierarchy

___
## Exploration 1: Delhi Pointer
![Delhi Pointer](https://user-images.githubusercontent.com/111482857/217438033-45bdd8f6-1e46-4e55-abc2-c7d56239cbf1.jpeg)
___
## Exploration 2: Population Density - Choropleth
![Population Blue](https://user-images.githubusercontent.com/111482857/217438145-06683530-a9fe-473c-bf3d-106be5f00eb9.png)
___
## Exploration 3: Airports of the World
![Airports of the world](https://user-images.githubusercontent.com/111482857/217440327-023e89e2-667c-4dc2-ad25-c7190795f610.jpeg)
___
## Exploration 4: Disputed Lines
![Dispited Lines](https://user-images.githubusercontent.com/111482857/217440378-1b0ba538-627c-42c6-b04b-4b4d3b8599b0.jpeg)
___
## Exploration 5: Airports & Destinations Hub & Spoke Method
![Airport Destination India Hub Spoke](https://user-images.githubusercontent.com/111482857/217727367-4469e408-7981-4417-b9c7-9f4757d24400.jpeg)
___
## Exploration 6: Airports of India Clip Method
![Airports Clipped](https://user-images.githubusercontent.com/111482857/217727490-197118bc-d609-4625-acd5-224258140707.jpeg)
___
## Exploration 7: Coastal Lines - Nautical Miles
![Coastal Lines](https://user-images.githubusercontent.com/111482857/217727576-a537cef0-f035-4049-a521-910ccf821db5.jpeg)
___
## Exploration 8: Oil and Fuel Pipelines of the World
![Oil and Fuel](https://user-images.githubusercontent.com/111482857/217727658-5aa3e0c4-9fc2-4dd8-8b7b-f1967d1bdc13.jpeg)
___

**Comment by Rucha-ux** [comment]
## BASICS ##

<img width="1120" alt="Screenshot 2023-02-08 at 11 27 27 PM" src="https://user-images.githubusercontent.com/75575294/217617925-1ca2f598-4bd0-4b0c-9610-d52b8961ee9a.png">

## RANDOM COLOR ##

<img width="963" alt="Screenshot 2023-02-08 at 11 29 08 PM" src="https://user-images.githubusercontent.com/75575294/217618010-d6518d88-2805-4337-9d04-61874786a81a.png">

## POPULATION ESTIMATE ##

<img width="943" alt="Screenshot 2023-02-08 at 11 36 31 PM" src="https://user-images.githubusercontent.com/75575294/217618191-80e24370-5fe7-4845-a05b-4d0512346828.png">

## GDP COMPARISON ##

<img width="970" alt="Screenshot 2023-02-08 at 11 33 08 PM" src="https://user-images.githubusercontent.com/75575294/217618262-a361e4b0-96c5-43c0-9eaf-86df3b063453.png">

## RIVERS OF INDIA ##

![Rivers-Of-India 2](https://user-images.githubusercontent.com/75575294/217626765-61d2fea7-c71b-4d2c-a8f0-681a98787c26.jpg)

## AIR ROUTES ##

<img width="766" alt="Screenshot 2023-02-08 at 11 48 18 PM" src="https://user-images.githubusercontent.com/75575294/217618395-8df17482-882e-439e-8e64-6d2880473c7d.png">

## OIL-NGL PIPELINES ##

![Frame 11](https://user-images.githubusercontent.com/75575294/217620797-8860dc08-adb0-4420-84a7-71996c26c042.jpg)


 ## LAYOUTING ##

![Frame 10](https://user-images.githubusercontent.com/75575294/217620278-c037dfea-5508-400b-a92f-06f9d09975a5.jpg)

**Comment by Rajeshm006** [comment]
![image](https://user-images.githubusercontent.com/111482817/217441226-44051cea-9695-48bf-8830-95931691078a.png)

![India_rivers_3](https://user-images.githubusercontent.com/111482817/217441301-ff0fecf8-bab5-4f3b-833b-9a65a6cc3191.png)

## Rivers_India
![image](https://github.com/mapschool/course/assets/111482817/c148d077-7019-47f3-9142-3d197e744a3b)


## Earthquake

![image](https://user-images.githubusercontent.com/111482817/217722889-aec7be02-70ae-44b3-98fa-0de546c7a498.png)


![earthquake](https://user-images.githubusercontent.com/111482817/217723969-2fa86190-167c-4803-9e82-09e7fab26d95.png)

## Airport_links
![image](https://github.com/mapschool/course/assets/111482817/bb909ad4-c1d4-43ac-87ce-fb8b1f63db78)

## tsunami_dataset
![image](https://github.com/mapschool/course/assets/111482817/53e62ddd-730e-446c-b15c-10656dd285e9)

## Air_pollution
![image](https://github.com/mapschool/course/assets/111482817/2e55eb9b-f599-49a1-ba7b-81ff156a7928)

## Mapping_my_selected_lake
Checking the Inlet and outlet of the selected lake using altitude:
![image](https://github.com/mapschool/course/assets/111482817/f34041b0-86c7-4465-97e5-e192bcbc8ad3)

![image](https://github.com/mapschool/course/assets/111482817/9961d44d-49b7-4f17-831d-a53215fce9c2)

## Cellphone Data
![image](https://github.com/mapschool/course/assets/111482817/e0182db4-ea5f-4ed8-ac46-e3d2b72292f2)

**Comment by dmrunal08** [comment]
**### Task 1: Plotting Rivers of India**

![Rivers of India](https://user-images.githubusercontent.com/111482876/217441715-9209e7ab-7f19-48b4-b294-eab09245871a.jpg)


### **Task 2: Earthquakes**

### **Its a WIP**

![earthquakes WIP](https://user-images.githubusercontent.com/111482876/217730435-267e2297-5c7f-4047-a8de-a7d0cbe78796.jpg)


Explorations:
![Fuel Network 2](https://github.com/mapschool/course/assets/111482876/a8f8ddb7-0f11-4c87-bc17-d96dd8b2c09e)
<img width="772" alt="Screenshot 2023-02-09 at 1 00 54 PM" src="https://github.com/mapschool/course/assets/111482876/3d27efb4-8fba-4960-9d80-92262c5421d1">
![Web 1920 – 1](https://github.com/mapschool/course/assets/111482876/7b37cb32-825d-400f-9582-2251c5b0a369)
![Web 1920 – 2](https://github.com/mapschool/course/assets/111482876/0069de2c-a40a-4a13-9b36-b2da5f7c3ea8)
![Web 1920 – 6](https://github.com/mapschool/course/assets/111482876/d831ea51-1b96-43bb-8dba-8ab4b615ca6a)




### **Its a WIP**
Scrolly:
LINK: https://xd.adobe.com/view/30455bd7-7d69-4ea4-a8f6-bb30d5904abe-6516/?fullscreen

PNG Version:
![Web 1920 – 7](https://github.com/mapschool/course/assets/111482876/de5ecfc3-c7de-49f3-bbad-5a03991795fd)

**Comment by geetanjalikhanna98** [comment]
# QGIS Explorations

_Geetanjali Khanna_


## Filtering in map (using Query Builder)

![Screenshot 2023-02-08 at 10 54](https://user-images.githubusercontent.com/36082594/217605950-7421f847-394b-442a-b109-e44ef7728171.png)





## Choropleth 1: Assigning colors from CSV file to Countries

![Screenshot 2023-02-07 at 3 31](https://user-images.githubusercontent.com/36082594/217605974-533d6ea6-5532-4313-841c-133f1cc222b4.png)





## Choropleth 2: Population Mapping of the World (Mapping population to color using Assistant)

![Screenshot 2023-02-08 at 10 57 1](https://user-images.githubusercontent.com/36082594/217606570-d6908a0e-9337-4f83-84b8-5910ac806bcf.png)





## Choropleth 3: GDP Mapping of the World (Mapping GDP to color using Graduated Symbols)

![Choropleth](https://user-images.githubusercontent.com/36082594/217608513-82666fd4-c1bf-46ed-8d79-d164e4f3da1e.png)






## Airports of the World: Mapping Elevation as Symbol Size

<img width="1072" alt="Screenshot 2023-02-08 at 11 21 1 (1)" src="https://user-images.githubusercontent.com/36082594/217612372-a88ead1d-2ddb-4341-8f84-b59b26295739.png">




## Rivers Map of India

[A4 - 1.pdf](https://github.com/mapschool/course/files/10688581/A4.-.1.pdf)

![A4 - 1 (3)](https://user-images.githubusercontent.com/36082594/217616047-26b8be5c-5c99-4640-8610-6b87ea2b93ee.jpg)








---

## Airport Routes 

![Screenshot 2023-02-08 at 3 37](https://user-images.githubusercontent.com/36082594/217607487-6b841901-d194-4b82-8d7c-638e8ac587d6.png)





## Pipelines

![Screenshot 2023-02-08 at 3 56](https://user-images.githubusercontent.com/36082594/217607710-99ee974f-b454-429e-a7dd-821a6e9f6459.png)

![Screenshot 2023-02-08 at 11 05 1](https://user-images.githubusercontent.com/36082594/217608097-ca46c4ce-bd83-4f19-8c40-210e68efc9e0.png)

---

# Narrative Cartography 

[Interactive Narrative Cartography]( https://www.figma.com/proto/QVWZJnzrdReDJm2xDSAv0e/Thematic-Interactive?type=design&node-id=25-45106&scaling=contain&page-id=0%3A1&starting-point-node-id=25%3A45106)

**Comment by speckx** [comment]
### Fill Color in World Map
Learnings-
Data defined channels like color, stroke color, weight with the help of expression builder

![random color function](https://user-images.githubusercontent.com/111493088/218448059-4299b3de-ff87-4808-ba7c-cd8abab456df.png)


### World GDP
Learnings-
Graduated symbols
Adding Legend
Projections
![GDP](https://user-images.githubusercontent.com/111493088/218446983-89946e26-115a-474d-9de0-19837bb6211b.png)

### Creating buffer of geographies
Learnings-
Reprojections, UTM
Processing tool
Geoprocessing tool
![buffer for geographies](https://user-images.githubusercontent.com/111493088/218449156-84b234bc-010a-476d-a1d7-d726a6c1a726.png)


### Gas Lines (based on capacity)- Using Assistant for linking data to channels.
Learnings-
Assistant

![gas lines](https://user-images.githubusercontent.com/111493088/218453393-e198f9bb-2d81-4f6a-890b-0db548ef1f74.png)
### Flight Routes
Learnings-
Expression builder

![Hyderabad](https://user-images.githubusercontent.com/111493088/218491001-2b75922f-2bea-4341-a4c8-43fc27a2bf10.png)

![From_figma](https://user-images.githubusercontent.com/111493088/218491038-178906a2-cbfc-4b3c-98d9-d15d3c6508f7.png)

### Particulate Pollution
Learnings-
raster data formats and importing
raster layer properties- symbology, histogram, no data values
manipulating color gradation to suit narrative - here we highlighted extreme pollution by exaggeration and manipulating data classification

![air_pollution_with_country_boundaries](https://user-images.githubusercontent.com/111493088/218456070-c070d73e-e2f3-4102-98f4-32b87e42826a.png)

### DEM files
Learnings-
Understanding DEMs
Render styles
Hill Shade, Scaling

![combined shaded](https://user-images.githubusercontent.com/111493088/218460082-16e22ba4-b759-4620-a888-a50b84511519.png)

### Trees of Banglore
Narrative theme
We constantly hear about the dwindling greens of Bengaluru. The consequences of it are well know ; ecological problems, urban heat island effect, loss of public greens etc. There is also a loss of heritage and identity that comes with mistreating the city's trees. The narrative traces back the trees to their origin which wasnt quite natural.

### Questions
How did a geographically arid and dry land turn into a lush urban forest ?
why were these trees/ groves made  and who was responsible?
At what rate are we losing our greens ?


### Concept

**Illustrations of Bengaluru in 1700s**
Lalbagh
![Lal_bagh_gardens1794](https://user-images.githubusercontent.com/111493088/225820095-3bb539ce-999f-47fb-8bb7-50b6b877ddae.jpg)

Nandi Hills
![Nandidrug1791_Mackenzie](https://user-images.githubusercontent.com/111493088/225820105-c04d5a93-1a48-4970-b1c5-a80ac9f22616.jpg)

**How a barren land turned into lush forest**
The trees were a result of a cultural / political agent rather than a natural process
1. The sacred groves planted near banks of Arkavati river
2. The trees imported by Deccan Sultanate
3. The botanical experiments during colonial period

**This book maps groves, trees and avenues of historical prominence**
![download](https://user-images.githubusercontent.com/111493088/225821583-6dcd1868-82e3-4910-8f48-71c527566667.jpg)


**But in the last 3 decades, the green cover Bengaluru has come down from 63% to 7 %**
![image](https://user-images.githubusercontent.com/111493088/225823273-cfd15bc6-ff80-4edf-ac07-adf40a9d3983.jpg)

**It is interesting to note that greens of cultural and heritage value managed to survive the urbanization**
![GoogleMapBF06aug2014](https://user-images.githubusercontent.com/111493088/225823484-d2267e36-ff74-49d6-b28c-c568b3dc0263.jpg)

**Narrative sketch**
![Untitled_Artwork (42)](https://user-images.githubusercontent.com/111493088/224349736-06572307-86e6-49e2-9c12-245cb4250726.jpg)
![Untitled_Artwork (41)](https://user-images.githubusercontent.com/111493088/224349769-313926e0-2da7-49ed-920b-012577876c12.jpg)

**NDVI index map calculated using raster processing from Landsat 8 images**

![banglore NDVI](https://user-images.githubusercontent.com/111493088/225222852-ba978767-0a68-44f8-80f4-295c1271fc29.png)

**Tree density - trees per person - 2014**
![tree_density](https://user-images.githubusercontent.com/111493088/225830633-e862c9bb-2e77-4623-b00a-fa4b373e67e3.png)

**Comment by ankita360** [comment]
![exp1](https://user-images.githubusercontent.com/123930284/226084747-57e6d102-d70d-4239-a6dc-dcb1790c4e66.png)
![exp2](https://user-images.githubusercontent.com/123930284/226084750-612938a6-26bb-41d9-9324-1d88c0971ded.png)
![exp3](https://user-images.githubusercontent.com/123930284/226084751-0a179621-ba97-4d54-a1c5-cf204c93ab39.png)
![exp4](https://user-images.githubusercontent.com/123930284/226084752-703a1f7c-a4a9-4348-acb3-aa92b3837f50.png)
![exp5](https://user-images.githubusercontent.com/123930284/226084753-475f2716-24cc-4bf9-a610-1374dac864ce.png)
![exp6](https://user-images.githubusercontent.com/123930284/226084756-c2a8d422-ea24-49fd-97c2-7a64c150a180.png)
![exp7](https://user-images.githubusercontent.com/123930284/226084757-4a8ac924-8829-4a0b-a321-a20dc7658bd6.png)

**Comment by kowsie** [comment]
![exploration](https://github.com/mapschool/course/assets/111482788/7924dc54-b316-49d1-bdde-df9b81360173)
![explo 2](https://github.com/mapschool/course/asse
![explo3](https://github.com/mapschool/course/assets/111482788/e6fd0a1c-957c-4604-8c12-bb7fd17a12c2)
ts/111482788/a6f9a0dd-d373-43b5-8e56-abcafd62667b)
![explo4](https://github.com/mapschool/course/assets/111482788/47ee72fd-7419-4b86-8b25-93abcb5ebe3b)
![explo5](https://github.com/mapschool/course/assets/111482788/99de10c8-4420-4cdb-bbd9-fd3a3dc3a5fb)
![explo7](https://github.com/mapschool/course/assets/111482788/3926430c-cf28-4be5-80ea-b8ddebb9eac2)
![7](https://github.com/mapschool/course/assets/111482788/e67101cb-af39-4bb1-9e55-35e861edd56b)

**Comment by Gagarina1** [comment]
Coloured maps -

![basic 1](https://github.com/mapschool/course/assets/111482715/3a6902ce-7471-4cdd-952b-f030c8875167)

Population estimation

![population est](https://github.com/mapschool/course/assets/111482715/917fb0a0-b229-44b7-af19-f10bdf0a469c)

Understanding Masking

![masking](https://github.com/mapschool/course/assets/111482715/7de679c5-6110-4079-8bae-1dc4f63b7bf6)

Airport routes

![airport routes](https://github.com/mapschool/course/assets/111482715/dcaf2493-e051-4e0b-bd98-bfc2face6c50)

Floods of India

![floods of india](https://github.com/mapschool/course/assets/111482715/76056e00-fb9a-4400-93a2-8f7224ea2648)
