### ISSUE TITLE
Map inspiration and critique

### ISSUE THREAD

**Issue by pkd2512** [mapschool/cartography#83]
Bring an example of map-based visualisation and discuss:
- the type of map/viz used
- the data being shown
- your takeaway from reading the visualisation
- what you love about it
- what you could do better

**Comment by Chinmayk79** [comment]
**Abolitionist Movement in Boston: Proximity and Action** (Combining Geographic Information Systems and Storytelling)
<img width="1132" alt="Screenshot 2024-01-30 at 10 22 45 AM" src="https://github.com/mapschool/course/assets/122165522/0e709ed4-85bb-4eac-a1ad-e946e3687900">

Interactive Link - https://www.esri.com/en-us/about/events/uc/agenda/virtual-map-gallery#/submission-detail/6478f1b7ad25b5fc017d4269

1. Idea or Purpose - To educate and inform about the city's history and the important part it played in the abolitionist movement. The map alone does not tell all about the abolitionist movement in the city.
2. Data Accuracy - Sources are mentioned in the data story with a disclaimer that data might be inaccurate someplace. 
3. Map design - The map can be more visually appealing, The Map gets pixelated when zoomed in. Interactive Past vs Present map Is present in the data story but not in the map (Major flaw). Map style can be customized better. 
4. Legends and labels - No legend for different types of places ( Alleys, chapels, congregation spaces). Detail on demand is present when selecting a dot on the map, the dialogue box opens up with the particular information about that spot.
5. Accessibility - No accessibility features present
6. Reading the data story is required to understand the topic in depth. (Visuals with descriptions can be incorporated within the interactive map.

**Comment by arunikasajith** [comment]
**Banksy Roadmap by André Oliveira**

Banksy is a pseudonymous England-based street artist, political activist, and film director whose real name and identity remain unconfirmed and the subject of speculation. Active since the 1990s, his satirical street art and subversive epigrams combine dark humour with graffiti executed in a distinctive stenciling technique. His works of political and social commentary have appeared on streets, walls, and bridges throughout the world. (Source: Wikipedia)

- **Type of map:** Locator map
- **Type of viz:** Proportional symbol map
- **Data shown:** Locations where Banksy's artworks are present (with roadmaps)

![banksy roadmap](https://github.com/mapschool/course/assets/126863213/a98c1d7c-b1b5-431a-b9e3-dd0559c88040)

What happens once I click on the point
![roadmap steps](https://github.com/mapschool/course/assets/126863213/d82c3588-38f1-4561-abdf-770861e6c59b)

Link to interactive map: https://public.tableau.com/app/profile/andr.oliveira8781/viz/Banksy/Home

**What I learned:**
- A general idea of where all, around the world, Banksy's artworks are present
- Locations preferred by the artist
- No. of artworks present in a certain place

**What I loved:**
- The contrasting colour scheme helped differentiate between the symbol and the base map
- The initial screen shows the silhouette (almost) of the base map and as you zoom in all the other elements like boundaries and roads are visible which helps in reducing cognitive overload
- The hover effect helps in learning more about a certain area at first glance

**What could be improved:**
- Only names of major areas relevant to the context should be shown in the first frame
- Visually, the symbols should be proportional
- Instead of circles, other symbols that could signify the number of artworks can be used
- The filter given in the map is confusing, so it could be improved by taking different variables and organized properly

**Comment by NomeshwariReddy** [comment]
<img width="1316" alt="Screenshot 2024-01-30 at 10 26 12 AM" src="https://github.com/mapschool/course/assets/126862650/9ce4063a-b530-4073-8cc1-e17b6c53a3a0">

Interactive link: https://pudding.cool/2022/11/upward-mobility/

**Comment by Eesha-2002** [comment]
### Migrant Journeys  
**Crossing the Sahara**

[map link](https://www.behance.net/gallery/88877867/Migrant-Journeys-Crossing-the-Sahara)
![Screenshot 2024-01-30 102411](https://github.com/mapschool/course/assets/126862702/e3534a0e-6599-4928-8d3c-6b511f055b95)

**Type of Map -** 
This is a symbol and locator map, showing number of migrants dying on routes, crossing the Sahara desert.

**Data Shown -**
The map has encoded the routes taken through the Sahara desert and number of people dying on those routes. The location of death is shown by a dot. One dot signifies one death and theconcentric circles around a dot signifies those number. The color encoded shows the reason of death.

**Key Takeaways -**
The map interestingly highlights the route on which most deaths happen, bringing to light the lack of medical and shelter help on these routes. The map also highlights the reasons for those deaths and brings to light the stories of these migrants.

**What I love about it -**
What I really like about the viz is that how those routes gets highlighted by just showing number of deaths on that route. I also like how they have treated the base map to give the effect of a dry desert, that also helps the color encoding of the dots and concentric circle stand out on the map.

**What can be done better-**
Since the map viz is a static map, its difficult to identify the exact location of deaths due to overlapping concentric circles. Also the concentric circles essentially just encode number of deaths, but because there is very less gap between each circle and they tend to cover an area on the map, it takes away attention from the point location and instead gives the effect of a region being affected, which is not the purpose of the symbol. In inset map to show the zoomed-in version of a particular area would help read the static map better.

**Comment by Meg-exe** [comment]
**Hawaii’s Beaches Are Disappearing**

![image](https://github.com/mapschool/course/assets/126862966/d1c0f3c2-05a0-415f-b6f5-e280f4098dd5)
Interactive Map Article: https://projects.propublica.org/hawaii-beach-loss/

**The type of map/viz used:**
Locator Symbol Map: Topographic Map showing locations using dots.

**The data being shown:**
A map which helps us to explore Shoreline exemptions in Hawaii, that have allowed property owners to keep old seawalls in place, build new ones and install mounds of emergency sandbags along the beaches within the past 20 years.

**Takeaway from reading the visualization:**
A map showing the beaches in Hawaii which are disappearing because of the destructive activity and approval by the government showing negligence to the environment and climate.

**What you love about it:**

- Detail on demand.
- Scroll and zoom into locations.
- Annotations throughout at important parts, while giving context.
- Search individual locations.

**What you could do better:**

- Marking the old shoreline to show the comparison with the current shoreline so people can clearly see the problem.
- Showcasing overtime the different data points.
- Combination of the first and second map.

**Comment by UtkarshSing98** [comment]
<img width="1920" alt="Slide 16_9 - 1 (7)" src="https://github.com/mapschool/course/assets/126862749/76b7d294-f168-4a35-8764-4a5858a9390e">

**Comment by ipsitaccc** [comment]
LANGUAGES IN THE WORLD by puffpuffproject.com

[Link to map](http://www.puffpuffproject.com/languages.html)

![image](https://github.com/mapschool/course/assets/126864097/12e8e18b-3d4a-4ed5-a0ea-e19cce34d39c)

Type of map used: Dots as pointers on a world map boundary with colour based grouping of language families

Data shown: Language in 10 language families, spoken by atleast 1% of the world population

Takeaway: Most of the (properly) surviving languages are from Europe, Asia and Africa; most of American indigenous languages don't exist at the same scale any more. With the interactivity, we can also see that some language families, like Indo-European span over continents and indicate a common origin of the languages in the family.

What I love about it: The topic itself is fascinating since it shows the origin of different language and language families. It also is a very simple and clear representation of the same.

What I could suggest as improvements: The map should be zoom-able as it is tough to see points at this scale. Maybe region/ country boundaries or indication could help in this context to relate the language to the region more. There can be more layers to this map showing where the current speakers are presently, to show how much each language/ family has traveled. The population of speakers could also be shown as a layer to show thriving/ declining languages. There is also some confusion regarding if the point is the point of origin or the point where the language is spoken.

**Comment by gmeenal98** [comment]
**LINK -** https://www.reuters.com/graphics/ISRAEL-PALESTINIANS/MAPS/zjvqedgdjvx/

<img width="1608" alt="Screenshot 2024-01-30 at 10 36 31 AM" src="https://github.com/mapschool/course/assets/127397480/f5f9b48e-4199-4cb9-8e83-1da242b96e4a">

.
**Data being shown -** 
Gaza Israel Conflict (Buildings damaged, refugee camps, hospitals, mosques, major roads)

**Your takeaway from reading the visualisation -**
- The impact of the conflict can be seen a lot more towards the Western part
- Refugee camps are set up according to the damage
- Most of the hospitals are in the zone with most damage

**What you love about it -** 
- The map reveals context at every scroll, limiting the amount of information thrown at the reader in one go
- At every scroll, the data shown is in the same colour as mentioned in the text on the map, which helps in relatability 
- The contrast of colours helps depict the information clearly

**what you could do better -**
- Moving the text on the map to the side to help make the map more promonent
- Letting user interact with the horizontal scrolling map on their own
- Give a bit more context of surroundings

**Comment by UtkarshSing98** [comment]
![Slide 16_9 - 1 (11)](https://github.com/mapschool/course/assets/126862749/f5a6c69b-afd4-4095-b098-f26ebfc35ad3)

https://dataidedesign.com/geospatial-and-visualization-specialist-craig-taylor-uses-3d-visualization-to-unpack-transit-data/

**Comment by SamruddhiBulbule** [comment]
https://www.mapnificent.net/london/#6/53.820/-1.791/5340/51.501/-0.128/5940/49.810/5.229/6600/49.525/6.416/900/49.282/6.768/7140/53.520/-1.130

### About map
Mapnificent shows you the area you can reach with public transport from any point in a given time. It is available for major cities in the US and world wide.

### What I liked?
The map's goal is clear and narrow. Adjustable control is minimalistic. The highlighted area looks like thrown paint and droplets can be examined by zooming in.

### What can be done better?
1. If user pins at the spot which is not supported by database or the spot which is not the main city, user should get feedback.
2. Once control is deleted there should be an option to get the control bar back instead of reloading it.

**Comment by tinnicreatesXOXO** [comment]
Sanjana Maiti

[Reprojected Destruction]
showing city-wide damage to buildings and infrastructure in Aleppo, Syria that he then projected onto figure-ground maps of Berlin and London. "The overall aim of the exercise " as stated on the [website](http://hanshack.com/aleppo/#modal-about)  "is to help viewers imagine the extent of the destruction that might have been visited upon the UK and German capitals had these cities stood at the centre of Syria's current conflict." In using location data to relocate the destruction wrought by the Syrian civil war  Hack reminds us that data visualizations are not only beautiful  but powerful communication tools.

https://hanshack.com/aleppo/#berlin

[
![Image 30-01-24 at 10 48 AM](https://github.com/mapschool/course/assets/126864929/76e673e1-dbf1-447d-b310-397f317a0b54)
](url)

What works:
1) Comparison in area.
2) Showing contrast with 2 major cities.
3) reprojected destruction.
4) Allows zoom to get perspective.

What lacks:
1) Intro to Syria and Aleppo.
2) Having a Syria real time version.
3) Annotations.

**Comment by NomeshwariReddy** [comment]
<img width="1316" alt="Screenshot 2024-01-30 at 10 26 12 AM" src="https://github.com/mapschool/course/assets/126862650/9ce4063a-b530-4073-8cc1-e17b6c53a3a0">

<img width="1486" alt="Screenshot 2024-01-30 at 10 36 49 AM" src="https://github.com/mapschool/course/assets/126862650/51bace0b-dbbf-4733-a186-77502dfa6b37">

<img width="1486" alt="Screenshot 2024-01-30 at 10 38 36 AM" src="https://github.com/mapschool/course/assets/126862650/510e649c-2715-4253-a261-cf66046c116c">


Interactive link: https://pudding.cool/2022/11/upward-mobility/

What is the map all about? 
The neighbourhood you grow up in has profound impact on your future economic success. How does the author's family migration or journey across various places in the country impacted him?

Research Question: Does moving out provide better opportunities? He mapped all the places he moved with his parents and grandparents. he calculated the outcome he might get,if he gets settled in that place.

Takeaways: 

He used 2 types of maps in the entire narrative.

One is outline map and dot map, Which i loved, it's a scrollytelling narrative and he used key map and original neighbourhood map to show the journey of each city he lived in, As you scroll down you can see the neighbourhood changing and the key map also representing the journey from one place to another.

Second one is: He mapped the migration his grandparents been through, the great american migration 1910-1940 that's where he used spike map, but there could be better representation of the map as it is little confusing and crowded at certain parts of the map, Plus it is a static map, so its bit more confusing. 

The solution could be like it could have been interactive map where when you hover you understand the metrics there or the base map could be chloropleth and of solid color and the spike could have the outline and the color coding which they did now.

What i love about the viz?

I love scrollytelling visualizations a lot! those are the best way to make user stick to the screen and understand things much more better.
I loved the way narration went, and the research question he picked. Very intresting, its always like every generation migrates somewhere for better opportunities. My grandparents did migrate, my father did, and my be i will too.
- The key map and the neighbourhood map are going well together and the pictures adn legend is also overlapping when you scroll gives a complete context of it.

**Comment by andriamarinus** [comment]
![image](https://github.com/mapschool/course/assets/126863696/e4c26ff3-e522-448c-ad77-05ecc2f2af47)
A map visualizing the **magnitude of covid deaths in the USA**
https://www.nytimes.com/interactive/2022/05/13/us/covid-deaths-us-one-million.html

What i like about the map
Deaths are represented by dots that are an integral part of the background that increases with the scrollytelling.
These dots then transition to compose an area chart which proceeds to transform to a locator map of USA

What could have been different
The map could've shown color variation during the transformation from area chart to locator map to differentiate the deaths caused due to the different waves of the pandemic. this could give us information on which areas were affected most during which wave of the pandemic.

**Comment by Surabhiiy** [comment]
![map](https://github.com/mapschool/course/assets/126863486/93ad3f51-9d7a-4d89-9d78-bff3b783528b)
https://www.visualcapitalist.com/map-worlds-ultra-rich-by-country/

1. Proportional symbol map- The size of the circles on the map represents the number of Ultra-high Net Worth Individuals in each country.

2. Data Being shown: It shows which countries have the highest number of UHNWIs (Ultra-high Net Worth Individuals).

3. My takeaway: The map very clearly the global distribution of extreme wealth, with the US and China dominating and Europe playing a significant role.
It also hints at emerging wealth pockets in Asia and Africa, though details require further exploration.

4. What I love: Simplicity and clarity: The map communicates its message effectively without drowning viewers in data. Clear title telling what the viz is about & Focus: clear Distribution of ultra-high net-worth individuals globally. Straightforward message: The map focuses on one message – where the world's ultra-rich are concentrated 
World map effectively shows distribution across continents. 
The color gradient used for the circles is easy to understand and provides a quick visual cue for comparing UHNWIs between different countries.

5. What could be better: Country labels can be visually overwhelming in some areas
Subdivide continents for improved context and comparison.
Allow filtering/highlighting countries based on specific UHNWIs range or projections.

**Comment by arifalimw** [comment]
### **How the Virus Got Out**
_By Jin Wu, Weiyi Cai, Derek Watkins and James Glanz_

Link: https://www.nytimes.com/interactive/2020/03/22/world/coronavirus-spread.html?ref=blog.duncangeere.com

<img width="889" alt="image" src="https://github.com/mapschool/course/assets/126864913/b9e86585-1f45-4122-a233-a2fc05013a1f">


1. **The type of map/viz used :** Locator, dot flow map?
2. **The data being shown:** The spread of coronavirus from Wuhan to the rest of the world
3. **Takeaway from reading the visualisation:** The story behind the spread of the virus from Wuhan and the reason behind the spread which is probably not taking immediate preventive measures which is evident from: "As the outbreak moved across China in early January, international travel continued as normal."
4. **What I Like about it:** The simplification of map and the way the story has been communicated
<img width="937" alt="image" src="https://github.com/mapschool/course/assets/126864913/d6662fe5-0ec3-4472-b886-64040f676ba2">
<img width="594" alt="image" src="https://github.com/mapschool/course/assets/126864913/2e738262-ee7d-458d-85d1-f6f6232050fc">

5. **What can be done better:** It is a good scrollytelling map.

**Comment by anjalikothari** [comment]
Link : https://news.sky.com/story/climate-change-the-people-forced-from-their-homes-by-floods-wildfires-storms-and-sea-level-rise-12355533

![image](https://github.com/mapschool/course/assets/126863089/f0c72a03-edaa-4186-9827-2ef29b79afab)
![image](https://github.com/mapschool/course/assets/126863089/c7f579c9-6cbd-4ad2-9c72-ef9356f2e3d7)
![image](https://github.com/mapschool/course/assets/126863089/9ce18652-d1a3-4ac1-866e-f6d6fa905428)

The type of map/viz used:
Proportional symbol through dots

The data being shown:
The displacement of people worldwide because of climate change.

Takeaway from reading the visualization:
- weather-related disasters in 2020 led to people in the poorest nations moving almost five times as often as those in richer ones.
- In low-income countries each severe weather event caused an average of almost 20,000 displacements last year, compared with 4,000 in the wealthiest nations,

What you love about it:
- showing colors for diff weather related disasters
- good scrolly telling

What you could do better:
- exact place/location is not mentioned
